"The GRASS Development Team, the addon authors, further contributors and\n"
"the user community have invested enormous efforts in making GRASS GIS\n"
"available to you. Please give credit where credit is due and cite GRASS\n"
"GIS and its addons when you use them for data analysis.\n"
"\n"
"For citation choices see below; for citing a particular GRASS GIS\n"
"module, you may cite the main author(s) along with the GRASS\n"
"Development Team.\n"
"\n"
"Choices for citing the main GRASS GIS software (update YEAR and version\n"
"number X.Y accordingly):\n"
"\n"
"* GRASS Development Team, YEAR. Geographic Resources Analysis Support\n"
"  System (GRASS) Software, Version X.Y. Open Source Geospatial\n"
"  Foundation. https://grass.osgeo.org\n"
"* GRASS Development Team, YEAR. Geographic Resources Analysis Support\n"
"  System (GRASS) Programmer's Manual. Open Source Geospatial Foundation.\n"
"  Electronic document: https://grass.osgeo.org/programming7\n"
"\n"
"Citing a GRASS GIS Addon (update AUTHOR(S), YEAR, Addon-NAME, and\n"
"version number X.Y accordingly):\n"
"\n"
"* AUTHOR(S), and GRASS Development Team, YEAR Addon-NAME. Geographic\n"
"  Resources Analysis Support System (GRASS) Software, Version X.Y.\n"
"  Open Source Geospatial Foundation.\n"
"  https://grass.osgeo.org/grass7/manuals/addons/Addon-NAME.html\n"
"\n"
"For other (scientific) references, see\n"
"\n"
"* https://grasswiki.osgeo.org/wiki/GRASS_Citation_Repository\n"
"\n"
"A BibTeX entry for LaTeX users is:\n"
"\n"
"@Manual{GRASS_GIS_software,\n"
"  title = {Geographic Resources Analysis Support System (GRASS) Software, Version X.Y},\n"
"  author = {{GRASS Development Team}},\n"
"  organization = {Open Source Geospatial Foundation},\n"
"  address = {USA},\n"
"  year = {YEAR},\n"
"  url = {https://grass.osgeo.org},\n"
"}\n"
