"Copyright and License Statement\n"
"\n"
"The Geographic Resources Analysis and Support System (GRASS)\n"
"Geographic Information System (GIS) is Copyright by members\n"
"of the GRASS Development Team.\n"
"\n"
"This program is free software; you can redistribute it and/or modify it\n"
"under the terms of the GNU General Public License as published by the\n"
"Free Software Foundation; either version 2 of the License, or (at your\n"
"option) any later version.\n"
"\n"
"Parts of GRASS are not copyright by the GRASS development team.\n"
"The original authors hold the copyrights and you have to abide\n"
"to their licensing terms where noted.\n"
"(Keep in mind that code linking into GRASS can only be distributed\n"
"if compatible with the GPL.)\n"
"\n"
"This program is distributed in the hope that it will be useful,\n"
"but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
"MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
"GNU General Public License (GPL) for more details.\n"
"\n"
"You should have received a copy of the GNU General Public License\n"
"along with this program; if not, write to the\n"
"  Free Software Foundation, Inc.,\n"
"  51 Franklin Street, Fifth Floor\n"
"  Boston, MA 02110-1301 USA\n"
"\n"
"Questions regarding GRASS GIS should be directed to the\n"
"GRASS Development Team at the following address:\n"
"\n"
" GRASS Development Team\n"
" c/o Markus Neteler\n"
" mundialis GmbH & Co. KG\n"
" Kölnstrasse 99 \n"
" 53111 Bonn, Germany\n"
" neteler AT osgeo.org\n"
"\n"
"Internet:  https://grass.osgeo.org\n"
