.TH d.fontlist 1 "" "GRASS 7.8.6RC3" "GRASS GIS User's Manual"
.SH NAME
\fI\fBd.fontlist\fR\fR  \- Lists the available fonts.
.SH KEYWORDS
display, settings
.SH SYNOPSIS
\fBd.fontlist\fR
.br
\fBd.fontlist \-\-help\fR
.br
\fBd.fontlist\fR [\-\fBlv\fR]  [\-\-\fBhelp\fR]  [\-\-\fBverbose\fR]  [\-\-\fBquiet\fR]  [\-\-\fBui\fR]
.SS Flags:
.IP "\fB\-l\fR" 4m
.br
List fonts (default; provided for compatibility with d.font)
.IP "\fB\-v\fR" 4m
.br
List fonts verbosely
.IP "\fB\-\-help\fR" 4m
.br
Print usage summary
.IP "\fB\-\-verbose\fR" 4m
.br
Verbose module output
.IP "\fB\-\-quiet\fR" 4m
.br
Quiet module output
.IP "\fB\-\-ui\fR" 4m
.br
Force launching GUI dialog
.SH DESCRIPTION
\fId.fontlist\fR outputs a list of available fonts for use with
GRASS display commands.
.SH SEE ALSO
\fId.text\fR
.SH AUTHOR
Glynn Clements
.SH SOURCE CODE
.PP
Available at: d.fontlist source code (history)
.PP
Main index |
Display index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2021
GRASS Development Team,
GRASS GIS 7.8.6RC3 Reference Manual
