.TH d.frame 1 "" "GRASS 7.8.7" "GRASS GIS User's Manual"
.SH NAME
\fI\fBd.frame.py\fR\fR  \- Manages display frames on the user\(cqs graphics monitor.
.SH KEYWORDS
display, graphics, monitors, frame
.SH SYNOPSIS
\fBd.frame.py\fR
.br
\fBd.frame.py \-\-help\fR
.br
\fBd.frame.py\fR [\-\fBcepa\fR] \fBframe\fR=\fIname\fR  [\fBat\fR=\fIbottom,top,left,right\fR]   [\-\-\fBoverwrite\fR]  [\-\-\fBhelp\fR]  [\-\-\fBverbose\fR]  [\-\-\fBquiet\fR]  [\-\-\fBui\fR]
.SS Flags:
.IP "\fB\-c\fR" 4m
.br
Create a new frame if doesn\(cqt exist and select
.IP "\fB\-e\fR" 4m
.br
Remove all frames, erase the screen and exit
.IP "\fB\-p\fR" 4m
.br
Print name of current frame and exit
.IP "\fB\-a\fR" 4m
.br
Print names of all frames including \(cqat\(cq position and exit
.IP "\fB\-\-overwrite\fR" 4m
.br
Allow output files to overwrite existing files
.IP "\fB\-\-help\fR" 4m
.br
Print usage summary
.IP "\fB\-\-verbose\fR" 4m
.br
Verbose module output
.IP "\fB\-\-quiet\fR" 4m
.br
Quiet module output
.IP "\fB\-\-ui\fR" 4m
.br
Force launching GUI dialog
.SS Parameters:
.IP "\fBframe\fR=\fIname\fR \fB[required]\fR" 4m
.br
Frame to be selected or created (if \-c flag is given)
.IP "\fBat\fR=\fIbottom,top,left,right\fR" 4m
.br
Screen coordinates in percent where to place the frame (0,0 is lower\-left)
.br
Implies only when \-c or \-\-overwrite flag is given
.br
Options: \fI0\-100\fR
.SH DESCRIPTION
\fId.frame\fR manages display frames on the current user\(cqs graphics
monitor. Graphics are displayed in rectangular frames on whatever
graphics monitor the user is currently directing GRASS display output
to (defined by \fId.mon\fR module). These
frames are created and managed with this module.
.PP
Note that GRASS frame contents \fIare not\fR retained when one
frame covers another. You cannot shuffle frames from top to bottom and
then back again. They simply define rectangular areas on the screen
where subsequent drawing will occur.
.SH NOTES
The coordinates for the \fBat\fR option are stated in the form
\fItop,bottom,left,right\fR values are in percent. The upper\-left
corner of the graphics monitor always is at location 0,0 while the
monitor\(cqs lower\-right corner is always at 100,100.
.PP
If the user has created multiple display frames that overlap one another,
whatever the user displays in the active frame will overwrite
those portions of the underlying frame where these frames overlap.
.SH EXAMPLE
.br
.nf
\fC
# start a new graphics monitor, the data will be rendered to
# /tmp/map.png image output file of size 600x540px
d.mon cairo out=/tmp/map.png width=600 height=540 \-\-o
# set up region
g.region raster=elevation
# remove all frames and erase the current graphics monitor
d.frame \-e
# create a first frame and display \(cqlanduse96_28m\(cq raster map including text label
# order: bottom,top,left,right \- in percent
d.frame \-c frame=first at=0,50,0,50
d.rast landuse96_28m
d.text text=\(cqLanduse\(cq bgcolor=220:220:220 color=black size=6
# create a second frame and display \(cqstreams\(cq vector map
d.frame \-c frame=second at=0,50,50,100
d.vect streams color=blue
d.text text=\(cqStreams\(cq bgcolor=220:220:220 color=black size=6
# create a third frame and display \(cqelevation\(cq raster map including text label and scale
d.frame \-c frame=third at=50,100,0,50
d.rast elevation
d.text text=\(cqElevation\(cq bgcolor=220:220:220 color=black size=6
d.barscale at=0,10 style=line bgcolor=none
# create a fourth frame and display RGB composition map including text label
d.frame \-c frame=fourth at=50,100,50,100
d.rgb red=lsat7_2002_30 green=lsat7_2002_20 blue=lsat7_2002_10
d.text text=\(cqRGB true colors\(cq bgcolor=220:220:220 color=black size=6
# release the current graphics monitor
d.mon \-r
\fR
.fi
.br
\fIFigure: d.frame example\fR
.SH SEE ALSO
\fI
d.erase,
d.info,
d.mon,
d.redraw
\fR
.PP
GRASS environment variables for
rendering (GRASS_RENDER_FRAME)
.SH AUTHOR
Martin Landa, Czech Technical University in Prague, Czech Republic
.PP
Based on \fId.frame\fR from GRASS 6:
.br
James Westervelt, U.S. Army Construction Engineering Research
Laboratory
.br
Michael Shapiro, U.S. Army Construction Engineering
Research Laboratory
.SH SOURCE CODE
.PP
Available at:
d.frame source code
(history)
.PP
Accessed: unknown
.PP
Main index |
Display index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2022
GRASS Development Team,
GRASS GIS 7.8.7 Reference Manual
