.TH index 1 "" "GRASS 7.8.7" "GRASS GIS User's Manual"
.SH GRASS GIS 7.8.7 Reference Manual
.PP
\fBGeographic Resources Analysis Support System\fR, commonly
referred to as GRASS GIS, is a Geographic
Information System (GIS) used for geospatial data management and
analysis, image processing, graphics/maps production, spatial
modeling, and visualization. GRASS is currently used in academic and
commercial settings around the world, as well as by many governmental
agencies and environmental consulting companies.
.PP
This reference manual details the use of modules distributed with
Geographic Resources Analysis Support System (GRASS), an open source
(GNU GPLed), image
processing and geographic information system (GIS).
.TS
expand;
lw60 lw1 lw60 lw1 lw60.
T{
 Quick Introduction
How to start with GRASS GIS
\fCIndex of topics and keywords\fR
Intro: projections and spatial transformations
\fCFAQ \- Frequently Asked Questions (Wiki)\fR
\fCGraphical index of functionality\fR
T}	 	T{
 Graphical User Interface
\fCwxGUI\fR
wxGUI components
wxGUI toolboxes
GUI commands
 Display
Display commands manual
Display drivers
T}	 	T{
 General
GRASS GIS startup manual
General commands manual
 Addons
Addons manual pages
 Programmer\(cqs Manual
Programmer\(cqs Manual
T}
.sp 1
T{
 Raster processing
Intro: 2D raster map processing
Raster commands manual
T}	 	T{
 3D raster processing
Intro: 3D raster map (voxel) processing
3D raster (voxel) commands manual
T}	 	T{
 Image processing
Intro: image processing
Imagery commands manual
T}
.sp 1
T{
 Vector processing
Intro: vector map processing and network analysis
Vector commands manual
GRASS ASCII vector format specification
T}	 	T{
 Database
Intro: database management
SQL support in GRASS GIS
Database commands manual
T}	 	T{
 Temporal processing
Intro: temporal data processing
Temporal commands manual
T}
.sp 1
T{
 Cartography
PostScript commands manual
wxGUI Cartographic Composer
T}	 	T{
 Miscellaneous & Variables
Miscellaneous commands manual
GRASS variables and environment variables
T}	 	T{
 Python
GRASS GIS Python library documentation
PyGRASS documentation
T}
.sp 1
.TE
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2022
GRASS Development Team,
GRASS GIS 7.8.7 Reference Manual
