.TH keywords 1 "" "GRASS 7.8.7" "GRASS GIS User's Manual"
.SH Keywords \- Index of GRASS GIS modules
.IP "\fB3D\fR" 4m
.br
v.drape, v.extrude, v.hull, v.out.postgis, v.surf.rst, v.to.3d, v.to.points, v.vol.rst
.IP "\fBACCA\fR" 4m
.br
i.landsat.acca
.IP "\fBaccumulation\fR" 4m
.br
r.series.accumulate, r.terraflow, r.watershed, t.rast.accdetect, t.rast.accumulate
.IP "\fBactual evapotranspiration\fR" 4m
.br
i.eb.eta
.IP "\fBaddons\fR" 4m
.br
g.extension
.IP "\fBaerial\fR" 4m
.br
g.gui.image2target, g.gui.photo2image
.IP "\fBaggregation\fR" 4m
.br
r.in.lidar, r.in.xyz, r.neighbors, r.patch, r.reclass.area, r.resamp.stats, r.series, r3.in.lidar, r3.in.xyz, r3.neighbors, t.rast.aggregate.ds, t.rast.aggregate, t.rast.neighbors, t.rast.series, v.neighbors
.IP "\fBalbedo\fR" 4m
.br
i.albedo
.IP "\fBalgebra\fR" 4m
.br
r.mapcalc, r.mapcalc.simple, r.mfilter, r.mode, r.neighbors, r.quantile, r.texture, r3.mapcalc, r3.neighbors, t.rast.algebra, t.rast.mapcalc, t.rast3d.algebra, t.rast3d.mapcalc, t.vect.algebra, v.neighbors
.IP "\fBanimation\fR" 4m
.br
g.gui.animation, r.out.mpeg
.IP "\fBarea\fR" 4m
.br
m.measure, v.buffer, v.centroids, v.clip, v.dissolve, v.in.ascii, v.to.db, v.to.lines, v.type
.IP "\fBarea estimation\fR" 4m
.br
r.surf.area
.IP "\fBarrow\fR" 4m
.br
d.northarrow, d.rast.arrow
.IP "\fBarticulation points\fR" 4m
.br
v.net.bridge
.IP "\fBASCII\fR" 4m
.br
r.in.ascii, r.in.xyz, r.out.ascii, r.out.xyz, r3.in.ascii, r3.out.ascii, v.in.ascii, v.out.ascii
.IP "\fBaspect\fR" 4m
.br
r.slope.aspect
.IP "\fBASTER\fR" 4m
.br
i.albedo, i.aster.toar, r.in.aster
.IP "\fBatmospheric correction\fR" 4m
.br
i.atcorr, i.landsat.toar
.IP "\fBattribute columns\fR" 4m
.br
v.info
.IP "\fBattribute table\fR" 4m
.br
db.columns, db.connect, db.copy, db.createdb, db.databases, db.describe, db.dropcolumn, db.dropdb, db.droptable, db.execute, db.in.ogr, db.out.ogr, db.select, db.tables, db.test, db.univar, g.gui.dbmgr, t.vect.db.select, v.class, v.db.addcolumn, v.db.addtable, v.db.connect, v.db.dropcolumn, v.db.droprow, v.db.droptable, v.db.join, v.db.reconnect.all, v.db.renamecolumn, v.db.select, v.db.univar, v.db.update, v.distance, v.to.db, v.univar, v.vect.stats, v.what.rast, v.what.rast3, v.what.strds, v.what.vect
.IP "\fBattribute update\fR" 4m
.br
v.db.update
.IP "\fBattributes\fR" 4m
.br
v.reclass
.IP "\fBautocorrelation\fR" 4m
.br
r.random.cells
.IP "\fBAVHRR\fR" 4m
.br
i.albedo
.IP "\fBazimuth\fR" 4m
.br
v.to.db
.IP "\fBbartlett\fR" 4m
.br
r.resamp.filter
.IP "\fBbicubic\fR" 4m
.br
r.resamp.bspline, r.resamp.interp
.IP "\fBbilinear\fR" 4m
.br
r.resamp.bspline, r.resamp.interp
.IP "\fBbinning\fR" 4m
.br
r.in.lidar, r.in.xyz, r3.in.lidar, r3.in.xyz
.IP "\fBbiomass\fR" 4m
.br
i.biomass
.IP "\fBbiophysical parameters\fR" 4m
.br
i.vi
.IP "\fBblackman\fR" 4m
.br
r.resamp.filter
.IP "\fBbounding box\fR" 4m
.br
v.to.db
.IP "\fBbox\fR" 4m
.br
r.resamp.filter
.IP "\fBbrightness temperature\fR" 4m
.br
i.aster.toar, i.landsat.toar
.IP "\fBBrovey\fR" 4m
.br
i.pansharpen
.IP "\fBbuffer\fR" 4m
.br
r.buffer, r.buffer.lowmem, r.circle, v.buffer, v.parallel
.IP "\fBcanonical components analysis\fR" 4m
.br
i.cca
.IP "\fBcartography\fR" 4m
.br
d.barscale, d.graph, d.grid, d.legend, d.legend.vect, d.linegraph, d.northarrow, d.rast.leg, d.text, d.title, d.vect.chart, d.vect.thematic
.IP "\fBcategory\fR" 4m
.br
r.category, v.category, v.to.db
.IP "\fBCCA\fR" 4m
.br
i.cca
.IP "\fBcentrality measures\fR" 4m
.br
v.net.centrality
.IP "\fBcentroid\fR" 4m
.br
v.centroids
.IP "\fBchart maps\fR" 4m
.br
d.vect.chart
.IP "\fBchoropleth map\fR" 4m
.br
d.vect.thematic
.IP "\fBcircle\fR" 4m
.br
r.circle, v.buffer
.IP "\fBciting\fR" 4m
.br
g.version
.IP "\fBclassification\fR" 4m
.br
g.gui.iclass, i.cluster, i.gensig, i.gensigset, i.maxlik, i.segment, i.smap, r.kappa, v.class
.IP "\fBclip\fR" 4m
.br
v.clip, v.overlay
.IP "\fBcloud detection\fR" 4m
.br
i.landsat.acca
.IP "\fBclump\fR" 4m
.br
v.cluster
.IP "\fBclumps\fR" 4m
.br
r.clump, r.volume
.IP "\fBcluster\fR" 4m
.br
v.cluster
.IP "\fBcolor table\fR" 4m
.br
d.colortable, r.colors, r.colors.out, r.colors.stddev, r.what.color, r3.colors, r3.colors.out, t.rast.colors, v.colors, v.colors.out
.IP "\fBcolor transformation\fR" 4m
.br
d.his, i.his.rgb, i.rgb.his, r.his
.IP "\fBcolors\fR" 4m
.br
d.colorlist, i.colors.enhance
.IP "\fBcompactness\fR" 4m
.br
v.to.db
.IP "\fBcomponents\fR" 4m
.br
v.net.components
.IP "\fBcomposite\fR" 4m
.br
r.blend, r.composite
.IP "\fBcompression\fR" 4m
.br
r.compress
.IP "\fBcomputational region\fR" 4m
.br
g.region
.IP "\fBconnection settings\fR" 4m
.br
db.connect, db.drivers, db.login
.IP "\fBconnectivity\fR" 4m
.br
v.net.connectivity
.IP "\fBcontour\fR" 4m
.br
t.rast.contour
.IP "\fBcontours\fR" 4m
.br
r.contour
.IP "\fBconversion\fR" 4m
.br
r.in.ascii, r.in.lidar, r.in.xyz, r.out.xyz, r.to.rast3, r.to.rast3elev, r.to.vect, r3.in.ascii, r3.in.lidar, r3.in.xyz, r3.out.ascii, r3.to.rast, t.rast.to.rast3, t.rast.to.vect, v.to.rast, v.to.rast3
.IP "\fBconvolution\fR" 4m
.br
r.resamp.filter
.IP "\fBcoordinates\fR" 4m
.br
v.to.db
.IP "\fBcopying\fR" 4m
.br
r.pack, r.unpack, v.pack, v.unpack
.IP "\fBcopyright\fR" 4m
.br
g.version
.IP "\fBcorrelation\fR" 4m
.br
d.correlate
.IP "\fBcost allocation\fR" 4m
.br
r.cost, r.walk, v.net.alloc, v.net.iso
.IP "\fBcost surface\fR" 4m
.br
r.cost, r.drain, r.path, r.walk
.IP "\fBcreate\fR" 4m
.br
t.create
.IP "\fBcreate location\fR" 4m
.br
g.proj, r.in.gdal, t.rast.import, t.vect.import, v.in.ogr
.IP "\fBcumulative costs\fR" 4m
.br
r.cost, r.spreadpath, r.walk
.IP "\fBcurvature\fR" 4m
.br
r.slope.aspect
.IP "\fBdecimation\fR" 4m
.br
v.decimate
.IP "\fBdensification\fR" 4m
.br
v.split
.IP "\fBdeposition\fR" 4m
.br
r.sim.sediment
.IP "\fBdepressions\fR" 4m
.br
r.fill.dir
.IP "\fBdiagram\fR" 4m
.br
d.correlate, d.polar
.IP "\fBdifference\fR" 4m
.br
v.overlay
.IP "\fBdigitizer\fR" 4m
.br
g.gui.vdigit
.IP "\fBdisplacement\fR" 4m
.br
v.generalize
.IP "\fBdissolve\fR" 4m
.br
v.dissolve, v.extract
.IP "\fBdistance\fR" 4m
.br
d.geodesic, d.rhumbline, m.cogo, m.measure, r.distance, r.grow.distance, r.grow, v.distance
.IP "\fBdiversity index\fR" 4m
.br
r.li.dominance, r.li.pielou, r.li.renyi, r.li.richness, r.li.shannon, r.li.simpson
.IP "\fBdownload\fR" 4m
.br
g.extension
.IP "\fBdrainage\fR" 4m
.br
r.watershed
.IP "\fBDXF\fR" 4m
.br
v.in.dxf, v.out.dxf
.IP "\fBE00\fR" 4m
.br
v.in.e00
.IP "\fBedges\fR" 4m
.br
i.zc, v.lidar.edgedetection
.IP "\fBediting\fR" 4m
.br
d.rast.edit, g.gui.vdigit, v.edit, v.type
.IP "\fBelevation\fR" 4m
.br
d.shade, r.fillnulls, r.in.aster, r.param.scale, r.plane, r.relief, r.shade
.IP "\fBemissivity\fR" 4m
.br
i.emissivity
.IP "\fBenergy balance\fR" 4m
.br
i.eb.eta, i.eb.evapfr, i.eb.hsebal01, i.eb.netrad, i.eb.soilheatflux, i.emissivity
.IP "\fBerosion\fR" 4m
.br
r.sim.sediment, r.uslek, r.usler
.IP "\fBevaporative fraction\fR" 4m
.br
i.eb.evapfr, i.eb.hsebal01
.IP "\fBevapotranspiration\fR" 4m
.br
i.evapo.mh, i.evapo.pm, i.evapo.pt, i.evapo.time
.IP "\fBexport\fR" 4m
.br
d.out.file, d.to.rast, db.out.ogr, r.colors.out, r.external.out, r.out.ascii, r.out.bin, r.out.gdal, r.out.gridatb, r.out.mat, r.out.mpeg, r.out.png, r.out.pov, r.out.ppm, r.out.ppm3, r.out.vrml, r.out.vtk, r.out.xyz, r.pack, r3.colors.out, r3.out.ascii, r3.out.bin, r3.out.v5d, r3.out.vtk, t.rast.export, t.rast.out.vtk, t.vect.export, v.colors.out, v.external.out, v.out.ascii, v.out.dxf, v.out.lidar, v.out.ogr, v.out.postgis, v.out.pov, v.out.svg, v.out.vtk, v.pack
.IP "\fBextensions\fR" 4m
.br
g.extension.all, g.extension
.IP "\fBextent\fR" 4m
.br
g.region, r.info, r3.info, t.info, v.info
.IP "\fBexternal\fR" 4m
.br
r.external, r.external.out, v.external, v.external.out
.IP "\fBextract\fR" 4m
.br
t.rast.extract, t.rast3d.extract, t.vect.extract, v.decimate, v.extract, v.outlier
.IP "\fBFast Fourier Transform\fR" 4m
.br
i.fft, i.ifft
.IP "\fBfill sinks\fR" 4m
.br
r.fill.dir
.IP "\fBfilter\fR" 4m
.br
r.mfilter, r.neighbors, r.resamp.filter, r3.neighbors, v.outlier
.IP "\fBFIR\fR" 4m
.br
r.resamp.filter
.IP "\fBfire\fR" 4m
.br
r.ros, r.spread, r.spreadpath
.IP "\fBflood\fR" 4m
.br
r.lake
.IP "\fBflow\fR" 4m
.br
r.sim.water, r.terraflow, v.net.flow
.IP "\fBfocal statistics\fR" 4m
.br
r.neighbors, r3.neighbors
.IP "\fBFPAR\fR" 4m
.br
i.biomass
.IP "\fBfractal\fR" 4m
.br
r.surf.fractal, v.to.db
.IP "\fBframe\fR" 4m
.br
d.frame
.IP "\fBfusion\fR" 4m
.br
i.pansharpen
.IP "\fBgauss\fR" 4m
.br
r.resamp.filter
.IP "\fBgazetteer\fR" 4m
.br
v.in.geonames
.IP "\fBGCP\fR" 4m
.br
g.gui.gcp, g.gui.image2target, g.gui.photo2image, i.ortho.transform, m.transform, v.transform
.IP "\fBgeneralization\fR" 4m
.br
v.decimate, v.generalize
.IP "\fBgeometry\fR" 4m
.br
g.gui.gcp, g.gui.image2target, g.gui.photo2image, i.image.mosaic, i.ortho.photo, i.rectify, r.circle, r.patch, r.region, r.thin, r.to.vect, v.buffer, v.build, v.build.polylines, v.clean, v.delaunay, v.drape, v.edit, v.extrude, v.generalize, v.hull, v.in.ogr, v.in.region, v.mkgrid, v.overlay, v.parallel, v.patch, v.perturb, v.rectify, v.report, v.segment, v.select, v.split, v.to.3d, v.to.db, v.to.lines, v.to.points, v.transform, v.type, v.univar, v.voronoi
.IP "\fBgeomorphology\fR" 4m
.br
r.param.scale
.IP "\fBgeomorphons\fR" 4m
.br
r.geomorphon
.IP "\fBgeorectification\fR" 4m
.br
g.gui.gcp, g.gui.image2target, g.gui.photo2image
.IP "\fBgradient\fR" 4m
.br
r3.gradient
.IP "\fBgraphical modeler\fR" 4m
.br
g.gui.gmodeler
.IP "\fBgraphics\fR" 4m
.br
d.erase, d.frame, d.his, d.info, d.mon, d.rast, d.redraw, d.rgb, d.vect, m.nviz.image, m.nviz.script, wxpyimgview
.IP "\fBgraticule\fR" 4m
.br
d.grid
.IP "\fBgreat circle\fR" 4m
.br
d.geodesic
.IP "\fBgrid\fR" 4m
.br
d.grid, v.mkgrid
.IP "\fBgroundwater flow\fR" 4m
.br
r.gwflow, r3.gwflow
.IP "\fBgrow\fR" 4m
.br
v.buffer
.IP "\fBGUI\fR" 4m
.br
g.gui.animation, g.gui.datacatalog, g.gui.dbmgr, g.gui.gcp, g.gui.gmodeler, g.gui, g.gui.iclass, g.gui.image2target, g.gui.mapswipe, g.gui.photo2image, g.gui.psmap, g.gui.rlisetup, g.gui.timeline, g.gui.tplot, g.gui.vdigit
.IP "\fBhamming\fR" 4m
.br
r.resamp.filter
.IP "\fBhann\fR" 4m
.br
r.resamp.filter
.IP "\fBhazard\fR" 4m
.br
r.lake, r.ros, r.spread
.IP "\fBheatmap\fR" 4m
.br
v.kernel
.IP "\fBhelp\fR" 4m
.br
g.manual
.IP "\fBhermite\fR" 4m
.br
r.resamp.filter
.IP "\fBhexagon\fR" 4m
.br
v.mkgrid
.IP "\fBhillshade\fR" 4m
.br
d.shade, r.relief, r.shade
.IP "\fBHIS\fR" 4m
.br
d.his, i.his.rgb, i.pansharpen, i.rgb.his, r.his
.IP "\fBhistogram\fR" 4m
.br
d.histogram
.IP "\fBhistory\fR" 4m
.br
r.info, v.info
.IP "\fBhotspot\fR" 4m
.br
v.kernel
.IP "\fBhydrology\fR" 4m
.br
r.basins.fill, r.carve, r.drain, r.fill.dir, r.flow, r.gwflow, r.lake, r.path, r.sim.sediment, r.sim.water, r.solute.transport, r.stream.extract, r.terraflow, r.topidx, r.topmodel, r.uslek, r.usler, r.water.outlet, r.watershed, r3.flow, r3.gwflow
.IP "\fBIDW\fR" 4m
.br
r.fill.stats, r.surf.idw, v.surf.idw
.IP "\fBIHS\fR" 4m
.br
d.his, i.his.rgb, i.pansharpen, i.rgb.his, r.his
.IP "\fBimagery quality assessment\fR" 4m
.br
i.modis.qc
.IP "\fBimport\fR" 4m
.br
db.in.ogr, i.in.spotvgt, r.external, r.import, r.in.ascii, r.in.aster, r.in.bin, r.in.gdal, r.in.gridatb, r.in.lidar, r.in.mat, r.in.png, r.in.poly, r.in.srtm, r.in.wms, r.in.xyz, r.proj, r.unpack, r3.in.ascii, r3.in.bin, r3.in.lidar, r3.in.v5d, r3.in.xyz, t.rast.import, t.vect.import, v.external, v.import, v.in.ascii, v.in.db, v.in.dxf, v.in.e00, v.in.geonames, v.in.lidar, v.in.lines, v.in.mapgen, v.in.ogr, v.in.wfs, v.proj, v.unpack
.IP "\fBinstallation\fR" 4m
.br
g.extension.all, g.extension
.IP "\fBinterpolation\fR" 4m
.br
r.fill.stats, r.fillnulls, r.resamp.bspline, r.resamp.interp, r.series.interp, r.surf.contour, r.surf.idw, t.rast.gapfill, v.surf.bspline, v.surf.idw, v.surf.rst, v.vol.rst
.IP "\fBintersection\fR" 4m
.br
v.overlay
.IP "\fBisolines\fR" 4m
.br
v.net.iso
.IP "\fBkernel density\fR" 4m
.br
v.kernel
.IP "\fBkernel filter\fR" 4m
.br
r.resamp.filter
.IP "\fBlanczos\fR" 4m
.br
r.resamp.filter, r.resamp.interp
.IP "\fBland flux\fR" 4m
.br
i.emissivity
.IP "\fBland surface temperature\fR" 4m
.br
i.modis.qc
.IP "\fBlandform\fR" 4m
.br
r.param.scale
.IP "\fBLandsat\fR" 4m
.br
i.albedo, i.landsat.acca, i.landsat.toar, i.tasscap
.IP "\fBlandscape structure analysis\fR" 4m
.br
g.gui.rlisetup, r.li.cwed, r.li.dominance, r.li.edgedensity, r.li.mpa, r.li.mps, r.li.padcv, r.li.padrange, r.li.padsd, r.li.patchdensity, r.li.patchnum, r.li.pielou, r.li.renyi, r.li.richness, r.li.shannon, r.li.shape, r.li.simpson
.IP "\fBlatitude\fR" 4m
.br
r.latlong
.IP "\fBlayer\fR" 4m
.br
v.category, v.db.connect
.IP "\fBlegend\fR" 4m
.br
d.legend, d.legend.vect, d.rast.leg, d.vect.thematic
.IP "\fBlength\fR" 4m
.br
v.to.db
.IP "\fBlevel1\fR" 4m
.br
d.vect, g.region, r.random, v.cluster, v.decimate, v.edit, v.external, v.in.ascii, v.in.dxf, v.in.lidar, v.info, v.patch, v.perturb, v.random, v.rectify
.IP "\fBlicense\fR" 4m
.br
g.version
.IP "\fBLIDAR\fR" 4m
.br
r.in.lidar, r.in.xyz, r3.in.lidar, r3.in.xyz, v.decimate, v.in.lidar, v.lidar.correction, v.lidar.edgedetection, v.lidar.growing, v.out.lidar, v.outlier, v.surf.bspline
.IP "\fBline\fR" 4m
.br
v.buffer, v.build.polylines, v.dissolve, v.edit, v.in.ascii, v.in.lines, v.parallel, v.to.lines, v.to.points, v.type
.IP "\fBline of sight\fR" 4m
.br
r.viewshed
.IP "\fBlinear reference system\fR" 4m
.br
v.lrs.create, v.lrs.label, v.lrs.segment, v.lrs.where
.IP "\fBlist\fR" 4m
.br
g.list, t.list, t.rast.list, t.rast3d.list, t.vect.list
.IP "\fBlongitude\fR" 4m
.br
r.latlong
.IP "\fBLOS\fR" 4m
.br
r.viewshed
.IP "\fBmachine vision geomorphometry\fR" 4m
.br
r.geomorphon
.IP "\fBmanual\fR" 4m
.br
g.manual
.IP "\fBmap annotations\fR" 4m
.br
d.northarrow, d.rast.arrow, d.rast.num
.IP "\fBmap management\fR" 4m
.br
g.access, g.copy, g.dirseps, g.filename, g.findetc, g.findfile, g.gui.datacatalog, g.list, g.remove, g.rename, i.group, i.target, r.compress, t.create, t.list, t.rast.list, t.rast3d.list, t.register, t.remove, t.rename, t.unregister, t.vect.list
.IP "\fBmask\fR" 4m
.br
r.mask, r3.mask
.IP "\fBMaximum Likelihood Classification\fR" 4m
.br
i.gensig, i.maxlik
.IP "\fBmeasurement\fR" 4m
.br
m.measure
.IP "\fBmerge\fR" 4m
.br
r.patch, t.merge
.IP "\fBmetadata\fR" 4m
.br
r.describe, r.info, r.region, r.support, r.timestamp, r3.info, r3.support, r3.timestamp, t.connect, t.downgrade, t.info, t.select, t.support, v.info, v.support, v.timestamp
.IP "\fBmiscellaneous\fR" 4m
.br
m.cogo, m.measure, m.nviz.image, m.nviz.script, m.proj, m.transform
.IP "\fBMLC\fR" 4m
.br
i.gensig, i.maxlik
.IP "\fBmodel\fR" 4m
.br
r.ros, r.sim.sediment, r.sim.water, r.spread, r.topmodel
.IP "\fBMODIS\fR" 4m
.br
i.albedo, i.modis.qc, i.tasscap
.IP "\fBmodules\fR" 4m
.br
g.search.modules
.IP "\fBmonitors\fR" 4m
.br
d.erase, d.frame, d.info, d.mon, d.redraw
.IP "\fBmosaic\fR" 4m
.br
r.buildvrt
.IP "\fBmosaicking\fR" 4m
.br
i.image.mosaic, r.patch
.IP "\fBmultispectral\fR" 4m
.br
i.oif, i.spectral
.IP "\fBNDVI\fR" 4m
.br
i.in.spotvgt, i.vi
.IP "\fBnearest neighbor\fR" 4m
.br
r.resamp.interp, r.resample
.IP "\fBneighbor\fR" 4m
.br
r.neighbors, r3.neighbors
.IP "\fBnet radiation\fR" 4m
.br
i.eb.netrad
.IP "\fBnetwork\fR" 4m
.br
d.path, v.lrs.create, v.lrs.label, v.lrs.segment, v.lrs.where, v.net.alloc, v.net.allpairs, v.net.bridge, v.net.centrality, v.net.components, v.net.connectivity, v.net.distance, v.net.flow, v.net, v.net.iso, v.net.path, v.net.salesman, v.net.spanningtree, v.net.steiner, v.net.timetable, v.net.visibility
.IP "\fBnetwork generalization\fR" 4m
.br
v.generalize
.IP "\fBnetwork maintenance\fR" 4m
.br
v.net
.IP "\fBno\-data filling\fR" 4m
.br
r.fill.stats, r.fillnulls, r.resamp.bspline, t.rast.gapfill, v.surf.rst, v.vol.rst
.IP "\fBnode\fR" 4m
.br
v.build.polylines, v.edit, v.segment, v.split, v.to.points
.IP "\fBnull data\fR" 4m
.br
r.null, r3.null
.IP "\fBobject recognition\fR" 4m
.br
i.segment
.IP "\fBOGC web services\fR" 4m
.br
r.in.wms, v.in.wfs
.IP "\fBOGC WFS\fR" 4m
.br
v.in.wfs
.IP "\fBOGC WMS\fR" 4m
.br
r.in.wms
.IP "\fBOGC WMTS\fR" 4m
.br
r.in.wms
.IP "\fBOGR\fR" 4m
.br
v.external, v.external.out, v.in.ogr, v.out.ogr
.IP "\fBorthorectify\fR" 4m
.br
i.ortho.camera, i.ortho.elev, i.ortho.init, i.ortho.photo, i.ortho.rectify, i.ortho.target, i.ortho.transform
.IP "\fBoutput\fR" 4m
.br
d.out.file, db.out.ogr, r.external.out, r.out.ascii, r.out.bin, r.out.gdal, r.out.gridatb, r.out.mat, r.out.mpeg, r.out.png, r.out.pov, r.out.ppm, r.out.ppm3, r.out.vrml, r.out.vtk, r.out.xyz, r3.out.ascii, r3.out.v5d, r3.out.vtk, t.rast.out.vtk, v.external.out, v.out.ascii, v.out.dxf, v.out.lidar, v.out.ogr, v.out.postgis, v.out.pov, v.out.svg, v.out.vtk
.IP "\fBoverland flow\fR" 4m
.br
r.sim.water
.IP "\fBpaint labels\fR" 4m
.br
d.labels, v.label, v.label.sa
.IP "\fBpatch index\fR" 4m
.br
r.li.cwed, r.li.edgedensity, r.li.mpa, r.li.mps, r.li.padcv, r.li.padrange, r.li.padsd, r.li.patchdensity, r.li.patchnum, r.li.shape
.IP "\fBpatching\fR" 4m
.br
r.patch
.IP "\fBPCA\fR" 4m
.br
i.pansharpen, i.pca
.IP "\fBpercentile\fR" 4m
.br
r.quantile, r.stats.quantile
.IP "\fBperimeter\fR" 4m
.br
v.to.db
.IP "\fBpermission\fR" 4m
.br
g.access
.IP "\fBphoto\fR" 4m
.br
g.gui.image2target, g.gui.photo2image
.IP "\fBplot\fR" 4m
.br
d.profile, g.gui.timeline, g.gui.tplot
.IP "\fBPNG\fR" 4m
.br
r.in.png, r.out.png
.IP "\fBpoint\fR" 4m
.br
v.edit, v.in.ascii, v.in.lines, v.segment, v.to.lines, v.to.points, v.type
.IP "\fBpoint cloud\fR" 4m
.br
v.cluster
.IP "\fBpoint density\fR" 4m
.br
v.kernel
.IP "\fBpoint pattern\fR" 4m
.br
v.kcv, v.mkgrid, v.normal, v.perturb, v.qcount, v.random
.IP "\fBpoints\fR" 4m
.br
v.decimate, v.in.db, v.kcv, v.normal, v.out.lidar
.IP "\fBpolar\fR" 4m
.br
m.cogo
.IP "\fBposition\fR" 4m
.br
d.where, r.what, v.what, v.what.rast, v.what.rast3, v.what.strds, v.what.vect
.IP "\fBPostGIS\fR" 4m
.br
v.external, v.external.out, v.out.postgis
.IP "\fBprincipal components analysis\fR" 4m
.br
i.pca
.IP "\fBprinting\fR" 4m
.br
g.gui.psmap, ps.map
.IP "\fBprofile\fR" 4m
.br
d.profile, r.profile, r.transect, r3.cross.rast, v.profile
.IP "\fBprojection\fR" 4m
.br
g.proj, m.proj, r.import, r.latlong, r.proj, v.import, v.proj
.IP "\fBproximity\fR" 4m
.br
r.grow.distance, r.grow
.IP "\fBquantile\fR" 4m
.br
r.quantile, r.stats.quantile
.IP "\fBquantization\fR" 4m
.br
r.quant
.IP "\fBquerying\fR" 4m
.br
d.where, i.spectral, r.what.color, r.what, v.rast.stats, v.what, v.what.rast, v.what.rast3, v.what.strds, v.what.vect
.IP "\fBradiance\fR" 4m
.br
i.aster.toar, i.atcorr, i.landsat.toar
.IP "\fBradiometric conversion\fR" 4m
.br
i.aster.toar, i.atcorr, i.landsat.toar
.IP "\fBrainfall\fR" 4m
.br
r.usler
.IP "\fBrandom\fR" 4m
.br
r.random.cells, r.random, r.random.surface, r.surf.gauss, r.surf.random, v.extract, v.perturb, v.random
.IP "\fBrasterization\fR" 4m
.br
v.to.rast
.IP "\fBrate of spread\fR" 4m
.br
r.ros
.IP "\fBreclass\fR" 4m
.br
r.clump
.IP "\fBreclassification\fR" 4m
.br
r.reclass, r.recode, v.reclass
.IP "\fBrecode categories\fR" 4m
.br
r.recode
.IP "\fBrectify\fR" 4m
.br
i.rectify, v.rectify
.IP "\fBreflectance\fR" 4m
.br
i.albedo, i.aster.toar, i.atcorr, i.landsat.toar, i.modis.qc
.IP "\fBregister\fR" 4m
.br
t.register
.IP "\fBregression\fR" 4m
.br
r.regression.line, r.regression.multi
.IP "\fBrelief\fR" 4m
.br
d.shade, r.relief, r.shade
.IP "\fBremove\fR" 4m
.br
g.remove, t.remove
.IP "\fBrename\fR" 4m
.br
g.rename, t.rename, v.db.renamecolumn
.IP "\fBresample\fR" 4m
.br
r.resamp.bspline, r.resamp.filter, r.resamp.interp, r.resamp.rst, r.resamp.stats, r.resample
.IP "\fBrescale\fR" 4m
.br
r.rescale.eq, r.rescale
.IP "\fBresolution\fR" 4m
.br
g.region
.IP "\fBRGB\fR" 4m
.br
d.his, d.rgb, i.colors.enhance, i.his.rgb, i.rgb.his, r.composite, r.his, r.rgb
.IP "\fBrhumbline\fR" 4m
.br
d.rhumbline
.IP "\fBRST\fR" 4m
.br
r.resamp.rst, v.surf.rst, v.vol.rst
.IP "\fBsalesman\fR" 4m
.br
v.net.salesman
.IP "\fBsampling\fR" 4m
.br
d.where, r.random.cells, r.random, t.rast.what, t.sample, t.vect.observe.strds, t.vect.what.strds, v.drape, v.extrude, v.kcv, v.random, v.rast.stats, v.sample, v.what.rast, v.what.rast3, v.what.strds, v.what.vect
.IP "\fBsatellite\fR" 4m
.br
i.albedo, i.aster.toar, i.atcorr, i.colors.enhance, i.landsat.acca, i.landsat.toar, i.modis.qc
.IP "\fBscripts\fR" 4m
.br
g.dirseps, g.filename, g.findetc, g.findfile, g.gisenv, g.message, g.tempfile
.IP "\fBsearch\fR" 4m
.br
g.list, g.search.modules
.IP "\fBsearch path\fR" 4m
.br
g.mapsets
.IP "\fBSEBAL\fR" 4m
.br
i.eb.eta, i.eb.evapfr, i.eb.hsebal01, i.eb.netrad, i.eb.soilheatflux
.IP "\fBsediment flow\fR" 4m
.br
r.sim.sediment
.IP "\fBsegment\fR" 4m
.br
v.segment, v.split
.IP "\fBsegmentation\fR" 4m
.br
i.segment, i.smap
.IP "\fBselect\fR" 4m
.br
t.vect.db.select, v.decimate, v.extract, v.outlier
.IP "\fBSentinel\fR" 4m
.br
i.tasscap
.IP "\fBseparate\fR" 4m
.br
r.rgb
.IP "\fBseries\fR" 4m
.br
r.patch, r.series.accumulate, r.series, r.series.interp, t.rast.series
.IP "\fBsettings\fR" 4m
.br
d.colorlist, d.font, d.fontlist, g.gisenv, g.mapset, g.mapsets, g.region, t.connect
.IP "\fBshadow\fR" 4m
.br
r.sun, r.sunmask
.IP "\fBsharpen\fR" 4m
.br
i.pansharpen
.IP "\fBshift\fR" 4m
.br
t.shift
.IP "\fBshortest path\fR" 4m
.br
d.geodesic, d.path, v.net.allpairs, v.net.distance, v.net.path, v.net.timetable, v.net.visibility
.IP "\fBshrink\fR" 4m
.br
v.buffer
.IP "\fBsides\fR" 4m
.br
v.to.db
.IP "\fBsignatures\fR" 4m
.br
g.gui.iclass, i.cluster, i.gensig, i.gensigset
.IP "\fBsimple\fR" 4m
.br
r.mapcalc.simple
.IP "\fBsimple features\fR" 4m
.br
v.out.postgis
.IP "\fBsimplification\fR" 4m
.br
v.generalize
.IP "\fBsinc\fR" 4m
.br
r.resamp.filter
.IP "\fBsink\fR" 4m
.br
r.fill.dir, r.terraflow
.IP "\fBsinuous\fR" 4m
.br
v.to.db
.IP "\fBskeleton\fR" 4m
.br
v.voronoi
.IP "\fBslope\fR" 4m
.br
r.slope.aspect, v.to.db
.IP "\fBSMAP\fR" 4m
.br
i.gensigset, i.smap
.IP "\fBsmoothing\fR" 4m
.br
v.generalize
.IP "\fBsnapping\fR" 4m
.br
t.snap, v.clean, v.in.ogr
.IP "\fBsoil\fR" 4m
.br
r.sim.sediment, r.sim.water, r.uslek, r.usler
.IP "\fBsoil heat flux\fR" 4m
.br
i.eb.soilheatflux
.IP "\fBsoil moisture\fR" 4m
.br
i.eb.evapfr, i.eb.hsebal01
.IP "\fBsolar\fR" 4m
.br
r.horizon, r.sun, r.sunhours, r.sunmask
.IP "\fBsolute transport\fR" 4m
.br
r.solute.transport
.IP "\fBspanning tree\fR" 4m
.br
v.net.spanningtree
.IP "\fBspatial query\fR" 4m
.br
v.overlay, v.select
.IP "\fBsplines\fR" 4m
.br
r.fillnulls, r.resamp.bspline, r.resamp.rst, v.surf.rst
.IP "\fBsplit\fR" 4m
.br
r.rgb
.IP "\fBSPOT\fR" 4m
.br
i.in.spotvgt
.IP "\fBspread\fR" 4m
.br
r.ros, r.spread
.IP "\fBSQL\fR" 4m
.br
db.copy, db.createdb, db.databases, db.dropdb, db.execute, db.select, v.db.select
.IP "\fBSRTM\fR" 4m
.br
r.in.srtm
.IP "\fBstatistics\fR" 4m
.br
d.correlate, d.histogram, db.univar, i.cca, i.oif, r.clump, r.coin, r.covar, r.cross, r.in.lidar, r.in.xyz, r.kappa, r.mfilter, r.mode, r.neighbors, r.quant, r.quantile, r.reclass.area, r.regression.line, r.regression.multi, r.report, r.statistics, r.stats, r.stats.quantile, r.stats.zonal, r.support.stats, r.surf.area, r.texture, r.univar, r3.in.lidar, r3.in.xyz, r3.neighbors, r3.stats, r3.univar, t.rast.univar, t.rast3d.univar, t.vect.univar, v.class, v.db.univar, v.kcv, v.neighbors, v.normal, v.outlier, v.perturb, v.qcount, v.random, v.rast.stats, v.report, v.univar
.IP "\fBsteiner tree\fR" 4m
.br
v.net.steiner
.IP "\fBstratified random sampling\fR" 4m
.br
v.random
.IP "\fBstream network\fR" 4m
.br
r.stream.extract, r.watershed
.IP "\fBstream power index\fR" 4m
.br
r.watershed
.IP "\fBsun energy\fR" 4m
.br
r.sun, r.sunhours
.IP "\fBsun position\fR" 4m
.br
r.horizon, r.sunhours, r.sunmask
.IP "\fBsupervised classification\fR" 4m
.br
g.gui.iclass, i.gensig, i.gensigset, i.smap
.IP "\fBsupport\fR" 4m
.br
g.message, g.tempfile, g.version
.IP "\fBsurface\fR" 4m
.br
r.contour, r.fill.stats, r.fillnulls, r.random.surface, r.resamp.bspline, r.surf.area, r.surf.contour, r.surf.fractal, r.surf.gauss, r.surf.idw, r.surf.random, v.surf.bspline, v.surf.idw, v.surf.rst, v.vol.rst
.IP "\fBsurface information\fR" 4m
.br
v.drape, v.what.rast, v.what.rast3
.IP "\fBTasseled Cap transformation\fR" 4m
.br
i.tasscap
.IP "\fBterrain\fR" 4m
.br
i.topo.corr, r.param.scale, r.relief, r.slope.aspect
.IP "\fBterrain patterns\fR" 4m
.br
r.geomorphon
.IP "\fBtexture\fR" 4m
.br
r.texture
.IP "\fBtiling\fR" 4m
.br
r.tile, r.tileset, r3.retile
.IP "\fBtime\fR" 4m
.br
r.timestamp, r3.timestamp, t.create, t.downgrade, t.info, t.list, t.merge, t.rast.accdetect, t.rast.accumulate, t.rast.aggregate.ds, t.rast.aggregate, t.rast.algebra, t.rast.colors, t.rast.contour, t.rast.export, t.rast.extract, t.rast.gapfill, t.rast.import, t.rast.list, t.rast.mapcalc, t.rast.neighbors, t.rast.out.vtk, t.rast.series, t.rast.to.rast3, t.rast.to.vect, t.rast.univar, t.rast.what, t.rast3d.algebra, t.rast3d.extract, t.rast3d.list, t.rast3d.mapcalc, t.rast3d.univar, t.register, t.remove, t.rename, t.sample, t.select, t.shift, t.snap, t.support, t.topology, t.unregister, t.vect.algebra, t.vect.db.select, t.vect.export, t.vect.extract, t.vect.import, t.vect.list, t.vect.observe.strds, t.vect.univar, t.vect.what.strds, v.timestamp, v.what.strds
.IP "\fBtime management\fR" 4m
.br
t.merge, t.shift, t.snap
.IP "\fBtimestamp\fR" 4m
.br
r.timestamp, r3.timestamp, v.timestamp
.IP "\fBtopographic correction\fR" 4m
.br
i.topo.corr
.IP "\fBtopographic index\fR" 4m
.br
r.topidx, r.watershed
.IP "\fBtopology\fR" 4m
.br
t.topology, v.build.all, v.build, v.build.polylines, v.clean, v.generalize, v.in.ogr, v.info, v.out.postgis
.IP "\fBtransect\fR" 4m
.br
r.profile, r.transect, v.profile
.IP "\fBtransformation\fR" 4m
.br
i.fft, i.ifft, i.ortho.transform, i.pca, i.tasscap, m.proj, m.transform, r.proj, v.proj, v.transform
.IP "\fBtriangulation\fR" 4m
.br
v.delaunay, v.voronoi
.IP "\fBtype casting\fR" 4m
.br
v.db.update
.IP "\fBunion\fR" 4m
.br
v.overlay
.IP "\fBunit test\fR" 4m
.br
test.r3flow, test.raster3d.lib
.IP "\fBunivariate statistics\fR" 4m
.br
r.resamp.stats, r.univar, r3.univar, v.rast.stats, v.univar, v.vect.stats
.IP "\fBunregister\fR" 4m
.br
t.unregister
.IP "\fBuser interface\fR" 4m
.br
g.gui
.IP "\fBvariables\fR" 4m
.br
g.gisenv
.IP "\fBvectorization\fR" 4m
.br
r.to.vect
.IP "\fBvegetation\fR" 4m
.br
i.modis.qc
.IP "\fBvegetation index\fR" 4m
.br
i.vi
.IP "\fBversion\fR" 4m
.br
g.version
.IP "\fBvertex\fR" 4m
.br
v.build.polylines, v.edit, v.segment, v.split, v.to.points
.IP "\fBviewshed\fR" 4m
.br
r.viewshed
.IP "\fBvirtual raster\fR" 4m
.br
r.buildvrt
.IP "\fBvisibility\fR" 4m
.br
v.net.visibility
.IP "\fBvisualization\fR" 4m
.br
d.shade, m.nviz.image, m.nviz.script, r.shade
.IP "\fBvolume\fR" 4m
.br
r.volume, r3.stats
.IP "\fBvoxel\fR" 4m
.br
r.to.rast3, r.to.rast3elev, r3.cross.rast, r3.flow, r3.gradient, r3.gwflow, r3.in.ascii, r3.in.bin, r3.in.v5d, r3.in.xyz, r3.info, r3.mask, r3.mkdspf, r3.neighbors, r3.null, r3.out.ascii, r3.out.bin, r3.out.v5d, r3.out.vtk, r3.retile, r3.stats, r3.support, r3.timestamp, r3.to.rast, t.rast.to.rast3, t.rast3d.algebra, t.rast3d.extract, t.rast3d.list, t.rast3d.mapcalc, t.rast3d.univar, v.to.rast3, v.vol.rst
.IP "\fBVRML\fR" 4m
.br
r.out.vrml
.IP "\fBVTK\fR" 4m
.br
r.out.vtk, r3.out.vtk, t.rast.out.vtk, v.out.vtk
.IP "\fBwatershed\fR" 4m
.br
r.basins.fill, r.water.outlet, r.watershed
.IP "\fBwetness\fR" 4m
.br
r.topidx
.IP "\fBworkflow\fR" 4m
.br
g.gui.gmodeler
.IP "\fBWorldview\fR" 4m
.br
i.tasscap
.IP "\fByield\fR" 4m
.br
i.biomass
.IP "\fBzonal statistics\fR" 4m
.br
r.statistics, r.stats.quantile, r.stats.zonal, r.univar, v.rast.stats, v.vect.stats
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2022
GRASS Development Team,
GRASS GIS 7.8.7 Reference Manual
