.TH miscellaneous_graphical 1 "" "GRASS 7.8.6RC3" "GRASS GIS User's Manual"
\&.img\-list {
margin: 0;
padding: 0;
list\-style\-type: none;
}
\&.img\-list li {
padding: 5px;
overflow: auto;
}
\&.img\-list li:hover {
background\-color: #eee;
}
\&.img\-list li a {
color: initial;
text\-decoration: none;
display: block;
}
\&.img\-list li img {
width: 10%;
float: left;
margin: 0 15px 0 0;
background: white;
object\-fit: scale\-down;
}
\&.img\-list li img.default\-img {
max\-height: 5ex;
}
\&.img\-list li .desc {
margin: 0px;
}
\&.img\-list li .name {
margin: 5px;
display: block;
color: #409940;
font\-weight: bold;
font\-style: italic;
}
.SH Graphical index of GRASS GIS modules
Go to miscellaneous introduction | topics
.PP
.SS Miscellaneous modules:
.RS 4n
.IP \(bu 4n
\fCm.cogo\fR \fCA simple utility for converting bearing and distance measurements to coordinates and vice versa.
.br
\fR
.IP \(bu 4n
\fCm.measure\fR \fCMeasures the lengths and areas of features.\fR
.IP \(bu 4n
\fCm.nviz.image\fR \fCCreates a 3D rendering of GIS data.
.br
\fR
.IP \(bu 4n
\fCm.nviz.script\fR \fCCreates fly\-through script to run in NVIZ.\fR
.IP \(bu 4n
\fCm.proj\fR \fCConverts coordinates from one projection to another (cs2cs frontend).\fR
.IP \(bu 4n
\fCm.transform\fR \fCComputes a coordinate transformation based on the control points.\fR
.RE
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2021
GRASS Development Team,
GRASS GIS 7.8.6RC3 Reference Manual
