.TH postscript_graphical 1 "" "GRASS 7.8.6RC3" "GRASS GIS User's Manual"
\&.img\-list {
margin: 0;
padding: 0;
list\-style\-type: none;
}
\&.img\-list li {
padding: 5px;
overflow: auto;
}
\&.img\-list li:hover {
background\-color: #eee;
}
\&.img\-list li a {
color: initial;
text\-decoration: none;
display: block;
}
\&.img\-list li img {
width: 10%;
float: left;
margin: 0 15px 0 0;
background: white;
object\-fit: scale\-down;
}
\&.img\-list li img.default\-img {
max\-height: 5ex;
}
\&.img\-list li .desc {
margin: 0px;
}
\&.img\-list li .name {
margin: 5px;
display: block;
color: #409940;
font\-weight: bold;
font\-style: italic;
}
.SH Graphical index of GRASS GIS modules
.SS Postscript modules:
.RS 4n
.IP \(bu 4n
\fCps.map\fR \fCProduces hardcopy PostScript map output.\fR
.RE
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2021
GRASS Development Team,
GRASS GIS 7.8.6RC3 Reference Manual
