.TH r.colors.stddev 1 "" "GRASS 7.8.7" "GRASS GIS User's Manual"
.SH NAME
\fI\fBr.colors.stddev.py\fR\fR  \- Sets color rules based on stddev from a raster map\(cqs mean value.
.SH KEYWORDS
raster, color table
.SH SYNOPSIS
\fBr.colors.stddev.py\fR
.br
\fBr.colors.stddev.py \-\-help\fR
.br
\fBr.colors.stddev.py\fR [\-\fBbz\fR] \fBmap\fR=\fIname\fR  [\-\-\fBhelp\fR]  [\-\-\fBverbose\fR]  [\-\-\fBquiet\fR]  [\-\-\fBui\fR]
.SS Flags:
.IP "\fB\-b\fR" 4m
.br
Color using standard deviation bands
.IP "\fB\-z\fR" 4m
.br
Force center at zero
.IP "\fB\-\-help\fR" 4m
.br
Print usage summary
.IP "\fB\-\-verbose\fR" 4m
.br
Verbose module output
.IP "\fB\-\-quiet\fR" 4m
.br
Quiet module output
.IP "\fB\-\-ui\fR" 4m
.br
Force launching GUI dialog
.SS Parameters:
.IP "\fBmap\fR=\fIname\fR \fB[required]\fR" 4m
.br
Name of raster map
.SH DESCRIPTION
\fIr.colors.stddev\fR set raster map color rules based on standard
deviations from a map\(cqs mean value, either as a continuous color gradient
or in color bands per standard deviation (S.D.) from the mean.
.PP
With the color band option values less that 1 S.D. from the mean are
colored green, within 1\-2 S.D. are colored yellow, within 2\-3 S.D. are
colored red, and beyond 3 S.D. are colored black.
.PP
For a differences map there is an option to lock the center of the color
table at zero. Values more than two S.D. below the mean will be colored blue;
values below the mean but less than 2 S.D. away will transition to white,
and above the mean the colors will simularly transition to full red at +2 S.D.
.SH EXAMPLE
North Carolina sample dataset location:
.br
.nf
\fC
g.region raster=elevation \-p
r.colors.stddev elevation
\fR
.fi
.SH SEE ALSO
\fI
r.colors,
r.univar,
v.colors
\fR
.SH AUTHOR
Hamish Bowman, \fIDunedin, New Zealand\fR
.SH SOURCE CODE
.PP
Available at:
r.colors.stddev source code
(history)
.PP
Accessed: unknown
.PP
Main index |
Raster index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2022
GRASS Development Team,
GRASS GIS 7.8.7 Reference Manual
