.TH r.info 1 "" "GRASS 7.8.6RC3" "GRASS GIS User's Manual"
.SH NAME
\fI\fBr.info\fR\fR  \- Outputs basic information about a raster map.
.SH KEYWORDS
raster, metadata, extent, history
.SH SYNOPSIS
\fBr.info\fR
.br
\fBr.info \-\-help\fR
.br
\fBr.info\fR [\-\fBgrseh\fR] \fBmap\fR=\fIname\fR  [\-\-\fBhelp\fR]  [\-\-\fBverbose\fR]  [\-\-\fBquiet\fR]  [\-\-\fBui\fR]
.SS Flags:
.IP "\fB\-g\fR" 4m
.br
Print raster array information in shell script style
.IP "\fB\-r\fR" 4m
.br
Print range in shell script style
.IP "\fB\-s\fR" 4m
.br
Print stats in shell script style
.IP "\fB\-e\fR" 4m
.br
Print extended metadata information in shell script style
.IP "\fB\-h\fR" 4m
.br
Print raster history instead of info
.IP "\fB\-\-help\fR" 4m
.br
Print usage summary
.IP "\fB\-\-verbose\fR" 4m
.br
Verbose module output
.IP "\fB\-\-quiet\fR" 4m
.br
Quiet module output
.IP "\fB\-\-ui\fR" 4m
.br
Force launching GUI dialog
.SS Parameters:
.IP "\fBmap\fR=\fIname\fR \fB[required]\fR" 4m
.br
Name of raster map
.SH DESCRIPTION
\fIr.info\fR reports some basic information about a
user\-specified raster map layer.  This map layer must exist
in the user\(cqs current mapset search path.  Information
about the map\(cqs boundaries, resolution, projection, data
type, category number, data base location and mapset,
the timestamp and history are put into a table and written to standard
output. The types of information listed can also be found
in the \fIcats\fR, \fIcellhd\fR, and \fIhist\fR
directories under the mapset in which the named map is
stored.
.PP
The user can save the tabular output to a file
by using the UNIX redirection mechanism (>); for example, the user
might save a report on the \fIsoils\fR map layer in a file called
\fIsoil.txt\fR by typing:
.br
.nf
\fC
r.info map=soils > soil.txt
\fR
.fi
.SH NOTES
On large maps, the total number of cells in the map may not be displayed
with an accurate number. This is only cosmetic.
.PP
Some standards (ISO\-C90) and compilers do not support the \(cqlong long\(cq type
as a 64\-bit type. In the case that GRASS GIS was built with such a compiler,
an accuracy message may be displayed in the output of \fIr.info\fR
after Total Cells.
.SH EXAMPLES
Below is a full report produced by \fIr.info\fR for the raster map
\fIslope\fR in the North Carolina sample data base:
.br
.nf
\fC
r.info slope
 +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
 | Map:      slope                          Date: Tue Nov  7 01:11:23 2006    |
 | Mapset:   PERMANENT                      Login of Creator: helena          |
 | Location: nc_spm_08_grass7                                                 |
 | DataBase: /grassdata                                                       |
 | Title:    South\-West Wake county: slope in degrees ( slope_ned10m )        |
 | Timestamp: none                                                            |
 |\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-|
 |                                                                            |
 |   Type of Map:  raster               Number of Categories: 255             |
 |   Data Type:    FCELL                                                      |
 |   Rows:         1350                                                       |
 |   Columns:      1500                                                       |
 |   Total Cells:  2025000                                                    |
 |        Projection: Lambert Conformal Conic                                 |
 |            N:     228500    S:     215000   Res:    10                     |
 |            E:     645000    W:     630000   Res:    10                     |
 |   Range of data:    min = 0  max = 38.68939                                |
 |                                                                            |
 |   Data Source:                                                             |
 |    raster elevation file elev_ned10m                                       |
 |                                                                            |
 |                                                                            |
 |   Data Description:                                                        |
 |    generated by r.slope.aspect                                             |
 |                                                                            |
 |   Comments:                                                                |
 |    slope map elev = elev_ned10m                                            |
 |    zfactor = 1.00 format = degrees                                         |
 |    min_slope = 0.000000                                              |
 |                                                                            |
 +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
\fR
.fi
Alternatively, the output from \fIr.info\fR may be confined to a more terse
subset of the available information by passing various flags to the module:
.PP
Output in shell script style, useful for eval (eval \(gar.info \-g slope\(ga):
.br
.nf
\fC
r.info \-g slope
north=228500
south=215000
east=645000
west=630000
nsres=10
ewres=10
rows=1350
cols=1500
cells=2025000
datatype=FCELL
ncats=255
\fR
.fi
.PP
Output the map data range:
.br
.nf
\fC
r.info \-r slope
min=0
max=38.68939
\fR
.fi
.PP
Output the extended map data metadata in shell style:
.br
.nf
\fC
r.info \-e slope
map=slope
mapset=PERMANENT
location=nc_spm_08_grass7
database=/grassdata
date=\(dqTue Nov  7 01:11:23 2006\(dq
creator=\(dqhelena\(dq
title=\(dqSouth\-West Wake county: slope in degrees (slope_ned10m)\(dq
timestamp=\(dqnone\(dq
units=\(dqnone\(dq
vdatum=\(dqnone\(dq
source1=\(dqraster elevation file elev_ned10m\(dq
source2=\(dq\(dq
description=\(dqgenerated by r.slope.aspect\(dq
comments=\(dqslope map elev = elev_ned10mzfactor = 1.00 format = degreesmin_slp_allowed = 0.000000\(dq
\fR
.fi
.SH SEE ALSO
\fI
g.mapsets,
r.coin,
r.describe,
r.report,
r.stats,
r.support,
r.univar,
r.what
\fR
.SH AUTHOR
Michael O\(cqShea,
U.S. Army Construction Engineering Research Laboratory
.SH SOURCE CODE
.PP
Available at: r.info source code (history)
.PP
Main index |
Raster index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2021
GRASS Development Team,
GRASS GIS 7.8.6RC3 Reference Manual
