.TH r.in.png 1 "" "GRASS 7.8.6RC3" "GRASS GIS User's Manual"
.SH NAME
\fI\fBr.in.png\fR\fR  \- Imports non\-georeferenced PNG format image.
.SH KEYWORDS
raster, import, PNG
.SH SYNOPSIS
\fBr.in.png\fR
.br
\fBr.in.png \-\-help\fR
.br
\fBr.in.png\fR [\-\fBfh\fR] \fBinput\fR=\fIname\fR \fBoutput\fR=\fIname\fR  [\fBtitle\fR=\fIstring\fR]   [\fBgamma\fR=\fIfloat\fR]   [\fBalpha\fR=\fIfloat\fR]   [\-\-\fBoverwrite\fR]  [\-\-\fBhelp\fR]  [\-\-\fBverbose\fR]  [\-\-\fBquiet\fR]  [\-\-\fBui\fR]
.SS Flags:
.IP "\fB\-f\fR" 4m
.br
Create floating\-point map (0.0 \- 1.0)
.IP "\fB\-h\fR" 4m
.br
Output image file header only and exit
.IP "\fB\-\-overwrite\fR" 4m
.br
Allow output files to overwrite existing files
.IP "\fB\-\-help\fR" 4m
.br
Print usage summary
.IP "\fB\-\-verbose\fR" 4m
.br
Verbose module output
.IP "\fB\-\-quiet\fR" 4m
.br
Quiet module output
.IP "\fB\-\-ui\fR" 4m
.br
Force launching GUI dialog
.SS Parameters:
.IP "\fBinput\fR=\fIname\fR \fB[required]\fR" 4m
.br
Name of input file
.IP "\fBoutput\fR=\fIname\fR \fB[required]\fR" 4m
.br
Name for output raster map
.IP "\fBtitle\fR=\fIstring\fR" 4m
.br
Title for created raster map
.IP "\fBgamma\fR=\fIfloat\fR" 4m
.br
Display gamma
.IP "\fBalpha\fR=\fIfloat\fR" 4m
.br
Alpha threshold
.SH DESCRIPTION
\fIr.in.png\fR imports a non\-georeferenced Portable Network Graphics (PNG) image
as a GRASS raster map. Georeferencing .wld files are not supported, for that
\fIr.import\fR can be used.
.SH NOTES
In order to assign georeferencing after import use \fIr.region\fR.
.SH SEE ALSO
\fI
r.import,
r.in.gdal,
r.out.png,
r.region
\fR
.SH AUTHORS
Michael Shapiro
.br
Alex Shevlakov
.br
Glynn Clements
.SH SOURCE CODE
.PP
Available at: r.in.png source code (history)
.PP
Main index |
Raster index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2021
GRASS Development Team,
GRASS GIS 7.8.6RC3 Reference Manual
