.TH r3.info 1 "" "GRASS 7.8.7" "GRASS GIS User's Manual"
.SH NAME
\fI\fBr3.info\fR\fR  \- Outputs basic information about a user\-specified 3D raster map layer.
.SH KEYWORDS
raster3d, metadata, voxel, extent
.SH SYNOPSIS
\fBr3.info\fR
.br
\fBr3.info \-\-help\fR
.br
\fBr3.info\fR [\-\fBgrh\fR] \fBmap\fR=\fIname\fR  [\-\-\fBhelp\fR]  [\-\-\fBverbose\fR]  [\-\-\fBquiet\fR]  [\-\-\fBui\fR]
.SS Flags:
.IP "\fB\-g\fR" 4m
.br
Print raster3d information in shell style
.IP "\fB\-r\fR" 4m
.br
Print range in shell style only
.IP "\fB\-h\fR" 4m
.br
Print raster history instead of info
.IP "\fB\-\-help\fR" 4m
.br
Print usage summary
.IP "\fB\-\-verbose\fR" 4m
.br
Verbose module output
.IP "\fB\-\-quiet\fR" 4m
.br
Quiet module output
.IP "\fB\-\-ui\fR" 4m
.br
Force launching GUI dialog
.SS Parameters:
.IP "\fBmap\fR=\fIname\fR \fB[required]\fR" 4m
.br
Name of 3D raster map
.SH DESCRIPTION
\fIr3.info\fR reports metadata and range of 3D voxel maps.
.SH SEE ALSO
\fI
r.info
\fR
.SH AUTHORS
Roman Waupotitsch, Michael Shapiro,
Helena Mitasova, Bill Brown, Lubos Mitas,
Jaro Hofierka
.SH SOURCE CODE
.PP
Available at:
r3.info source code
(history)
.PP
Accessed: unknown
.PP
Main index |
3D raster index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2022
GRASS Development Team,
GRASS GIS 7.8.7 Reference Manual
