.TH t.info 1 "" "GRASS 7.8.7" "GRASS GIS User's Manual"
.SH NAME
\fI\fBt.info.py\fR\fR  \- Lists information about space time datasets and maps.
.SH KEYWORDS
temporal, metadata, extent, time
.SH SYNOPSIS
\fBt.info.py\fR
.br
\fBt.info.py \-\-help\fR
.br
\fBt.info.py\fR [\-\fBghd\fR] \fBinput\fR=\fIname\fR  [\fBtype\fR=\fIname\fR]   [\-\-\fBhelp\fR]  [\-\-\fBverbose\fR]  [\-\-\fBquiet\fR]  [\-\-\fBui\fR]
.SS Flags:
.IP "\fB\-g\fR" 4m
.br
Print in shell script style
.IP "\fB\-h\fR" 4m
.br
Print history information in human readable shell style for space time datasets
.IP "\fB\-d\fR" 4m
.br
Print information about the temporal DBMI interface and exit
.IP "\fB\-\-help\fR" 4m
.br
Print usage summary
.IP "\fB\-\-verbose\fR" 4m
.br
Verbose module output
.IP "\fB\-\-quiet\fR" 4m
.br
Quiet module output
.IP "\fB\-\-ui\fR" 4m
.br
Force launching GUI dialog
.SS Parameters:
.IP "\fBinput\fR=\fIname\fR \fB[required]\fR" 4m
.br
Name of an existing space time dataset or map
.IP "\fBtype\fR=\fIname\fR" 4m
.br
Type of the input space time dataset
.br
Options: \fIstrds,  str3ds,  stvds,  raster,  raster_3d,  vector\fR
.br
Default: \fIstrds\fR
.SH DESCRIPTION
\fIt.info\fR reports information about any dataset that is
registered in the temporal database in human readable or shell script
style. Datasets are raster, 3D raster and vector maps as well as their
corresponding space time datasets (STRDS, STR3DS and STVDS). This
module reports the information that are stored in the temporal
database. These are basic information (id, name, mapset, creator,
creation time, temporal type), the temporal and spatial extent and
dataset type specific metadata. The user has to utilize \fIr.info\fR,
\fIr3.info\fR, \fIv.info\fR to report detailed information about
raster, 3D raster and vector maps, since not all map specific
information and metadata are stored in the temporal database.
.PP
In addition, information about the chosen temporal database backend
can be reported.
.SH NOTES
Temporal databases stored in other mapsets can be used as long as they
are in the user\(cqs current mapset search path (managed with
g.mapsets).
.SH EXAMPLES
.SS Temporal DBMI information
In order to obtain information about temporal DBMI backend, run:
.br
.nf
\fC
t.info \-d
 +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- Temporal DBMI backend information \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
 | DBMI Python interface:...... sqlite3
 | Temporal database string:... /grassdata/nc_spm_temporal_workshop/climate_2000_2012/tgis/sqlite.db
 | SQL template path:.......... /usr/local/grass\-7.0.0/etc/sql
 | tgis_db_version .......... 2
 | creation_time .......... 2014\-11\-22 20:06:46.863733
 | tgis_version .......... 2
 +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
\fR
.fi
.SS Space time dataset information
In order to obtain information about a space time dataset, run:
.br
.nf
\fC
t.info input=tempmean_monthly
 +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- Space Time Raster Dataset \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
 |                                                                            |
 +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- Basic information \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
 | Id: ........................ tempmean_monthly@climate_2000_2012
 | Name: ...................... tempmean_monthly
 | Mapset: .................... climate_2000_2012
 | Creator: ................... lucadelu
 | Temporal type: ............. absolute
 | Creation time: ............. 2014\-11\-27 08:50:48.443229
 | Modification time:.......... 2014\-11\-27 09:44:32.800282
 | Semantic type:.............. mean
 +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- Absolute time \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
 | Start time:................. 2009\-01\-01 00:00:00
 | End time:................... 2013\-01\-01 00:00:00
 | Granularity:................ 1 month
 | Temporal type of maps:...... interval
 +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- Spatial extent \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
 | North:...................... 320000.0
 | South:...................... 10000.0
 | East:.. .................... 935000.0
 | West:....................... 120000.0
 | Top:........................ 0.0
 | Bottom:..................... 0.0
 +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- Metadata information \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
 | Raster register table:...... raster_map_register_d567423784c740bea1fba75dc7c0fa3d
 | North\-South resolution min:. 500.0
 | North\-South resolution max:. 500.0
 | East\-west resolution min:... 500.0
 | East\-west resolution max:... 500.0
 | Minimum value min:.......... \-6.464337
 | Minimum value max:.......... 18.54137
 | Maximum value min:.......... 4.247691
 | Maximum value max:.......... 28.805381
 | Aggregation type:........... None
 | Number of registered maps:.. 48
 |
 | Title:
 | Monthly precipitation
 | Description:
 | Dataset with monthly precipitation
 | Command history:
 | # 2014\-11\-27 08:50:48
 | t.create type=\(dqstrds\(dq temporaltype=\(dqabsolute\(dq
 |     output=\(dqtempmean_monthly\(dq title=\(dqMonthly precipitation\(dq
 |     description=\(dqDataset with monthly precipitation\(dq
 | # 2014\-11\-27 09:44:32
 | t.register \-i type=\(dqrast\(dq input=\(dqtempmean_monthly\(dq maps=\(dq2009_01_tempmean,...,2012_12_tempmean\(dq start=\(dq2009\-01\-01\(dq increment=\(dq1 months\(dq
 |
 +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
\fR
.fi
The \(dqgranularity\(dq is the smallest gap size between the found time instances, i.e.
it the greatest common divisor between all gaps in the time series.
.SS Temporal maps information
In order to obtain information about a map in a space time dataset, run:
.br
.nf
\fC
t.info input=2009_01_tempmean type=raster
 +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- Raster Dataset \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
 |                                                                            |
 +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- Basic information \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
 | Id: ........................ 2009_01_tempmean@climate_2000_2012
 | Name: ...................... 2009_01_tempmean
 | Mapset: .................... climate_2000_2012
 | Creator: ................... lucadelu
 | Temporal type: ............. absolute
 | Creation time: ............. 2014\-11\-27 09:44:26.280147
 +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- Absolute time \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
 | Start time:................. 2009\-01\-01 00:00:00
 | End time:................... 2009\-02\-01 00:00:00
 +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- Spatial extent \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
 | North:...................... 320000.0
 | South:...................... 10000.0
 | East:.. .................... 935000.0
 | West:....................... 120000.0
 | Top:........................ 0.0
 | Bottom:..................... 0.0
 +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- Metadata information \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
 | Datatype:................... DCELL
 | Number of columns:.......... 620
 | Number of rows:............. 1630
 | Number of cells:............ 1010600
 | North\-South resolution:..... 500.0
 | East\-west resolution:....... 500.0
 | Minimum value:.............. \-3.380823
 | Maximum value:.............. 7.426054
 | Registered datasets ........ tempmean_monthly@climate_2000_2012
 +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
\fR
.fi
.SH SEE ALSO
\fI
t.create,
t.list,
t.register,
r.info,
r3.info,
v.info
\fR
.SH AUTHOR
Sören Gebbert, Thünen Institute of Climate\-Smart Agriculture
.SH SOURCE CODE
.PP
Available at:
t.info source code
(history)
.PP
Accessed: unknown
.PP
Main index |
Temporal index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2022
GRASS Development Team,
GRASS GIS 7.8.7 Reference Manual
