.TH t.rast.univar 1 "" "GRASS 7.8.6RC3" "GRASS GIS User's Manual"
.SH NAME
\fI\fBt.rast.univar.py\fR\fR  \- Calculates univariate statistics from the non\-null cells for each registered raster map of a space time raster dataset.
.SH KEYWORDS
temporal, statistics, raster, time
.SH SYNOPSIS
\fBt.rast.univar.py\fR
.br
\fBt.rast.univar.py \-\-help\fR
.br
\fBt.rast.univar.py\fR [\-\fBeru\fR] \fBinput\fR=\fIname\fR  [\fBoutput\fR=\fIname\fR]   [\fBwhere\fR=\fIsql_query\fR]   [\fBseparator\fR=\fIcharacter\fR]   [\-\-\fBoverwrite\fR]  [\-\-\fBhelp\fR]  [\-\-\fBverbose\fR]  [\-\-\fBquiet\fR]  [\-\-\fBui\fR]
.SS Flags:
.IP "\fB\-e\fR" 4m
.br
Calculate extended statistics
.IP "\fB\-r\fR" 4m
.br
Ignore the current region settings and use the raster map regions for univar statistical calculation
.IP "\fB\-u\fR" 4m
.br
Suppress printing of column names
.IP "\fB\-\-overwrite\fR" 4m
.br
Allow output files to overwrite existing files
.IP "\fB\-\-help\fR" 4m
.br
Print usage summary
.IP "\fB\-\-verbose\fR" 4m
.br
Verbose module output
.IP "\fB\-\-quiet\fR" 4m
.br
Quiet module output
.IP "\fB\-\-ui\fR" 4m
.br
Force launching GUI dialog
.SS Parameters:
.IP "\fBinput\fR=\fIname\fR \fB[required]\fR" 4m
.br
Name of the input space time raster dataset
.IP "\fBoutput\fR=\fIname\fR" 4m
.br
Name for output file
.IP "\fBwhere\fR=\fIsql_query\fR" 4m
.br
WHERE conditions of SQL statement without \(cqwhere\(cq keyword used in the temporal GIS framework
.br
Example: start_time > \(cq2001\-01\-01 12:30:00\(cq
.IP "\fBseparator\fR=\fIcharacter\fR" 4m
.br
Field separator character between the output columns
.br
Special characters: pipe, comma, space, tab, newline
.br
Default: \fIpipe\fR
.SH DESCRIPTION
\fIt.rast.univar\fR calculates univariate statistics from the
non\-null cells for each registered raster map of a space time raster
dataset.
.PP
By default it returns the name of the map, the start and end date of
dataset and the following values: mean, minimum and maximum vale,
mean_of_abs, standard deviation, variance, coeff_var, number of null
cells, total number of cell.
.PP
Using the \fIe\fR flag it can calculate also extended statistics:
first quartile, median value, third quartile and percentile 90.
.SH EXAMPLE
Obtain the univariate statistics for the raster space time dataset
\(dqtempmean_monthly\(dq (precision reduced to 2 decimals in this example):
.br
.nf
\fC
t.rast.univar \-e tempmean_monthly
id|start|end|mean|min|max|mean_of_abs|stddev|variance|coeff_var|sum|null_cells|cells|first_quartile|median|third_quartile|percentile_90
2009_01_tempmean@climate_2009_2012|2009\-01\-01 00:00:00|2009\-02\-01 00:00:00|3.90|\-3.38|7.43|3.95|1.79|3.20|45.91|1977967.31|503233|1010600|2.80|3.92|5.21|6.23
2009_02_tempmean@climate_2009_2012|2009\-02\-01 00:00:00|2009\-03\-01 00:00:00|5.91|\-1.82|8.01|5.92|1.63|2.65|27.53|2999555.60|503233|1010600|5.44|6.26|7.07|7.48
\&...
2012_11_tempmean@climate_2009_2012|2012\-11\-01 00:00:00|2012\-12\-01 00:00:00|8.03|1.79|10.91|8.03|1.32|1.73|16.41|4072472.77|503233|1010600|7.49|8.13|8.96|9.48
2012_12_tempmean@climate_2009_2012|2012\-12\-01 00:00:00|2013\-01\-01 00:00:00|8.71|1.76|11.98|8.71|1.72|2.95|19.74|4418403.77|503233|1010600|7.84|8.95|9.99|10.67
\fR
.fi
.SH SEE ALSO
\fI
t.create,
t.info
\fR
.SH AUTHOR
Sören Gebbert, Thünen Institute of Climate\-Smart Agriculture
.SH SOURCE CODE
.PP
Available at: t.rast.univar source code (history)
.PP
Main index |
Temporal index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2021
GRASS Development Team,
GRASS GIS 7.8.6RC3 Reference Manual
