.TH t.snap 1 "" "GRASS 7.8.6RC3" "GRASS GIS User's Manual"
.SH NAME
\fI\fBt.snap.py\fR\fR  \- Snaps temporally the maps of a space time dataset.
.SH KEYWORDS
temporal, time management, snapping, time
.SH SYNOPSIS
\fBt.snap.py\fR
.br
\fBt.snap.py \-\-help\fR
.br
\fBt.snap.py\fR \fBinput\fR=\fIname\fR  [\fBtype\fR=\fIname\fR]   [\-\-\fBhelp\fR]  [\-\-\fBverbose\fR]  [\-\-\fBquiet\fR]  [\-\-\fBui\fR]
.SS Flags:
.IP "\fB\-\-help\fR" 4m
.br
Print usage summary
.IP "\fB\-\-verbose\fR" 4m
.br
Verbose module output
.IP "\fB\-\-quiet\fR" 4m
.br
Quiet module output
.IP "\fB\-\-ui\fR" 4m
.br
Force launching GUI dialog
.SS Parameters:
.IP "\fBinput\fR=\fIname\fR \fB[required]\fR" 4m
.br
Name of an existing space time dataset
.IP "\fBtype\fR=\fIname\fR" 4m
.br
Type of the input space time dataset
.br
Options: \fIstrds, stvds, str3ds\fR
.br
Default: \fIstrds\fR
.SH DESCRIPTION
\fIt.snap\fR is designed to convert time instances of maps into time
intervals or to create valid temporal topologies for space time
datasets. Raster, 3D raster and vector space time datasets are
supported with absolute and relative time.
.PP
This module \(dqsnaps\(dq the end time of each registered map of a space time
dataset to the start time of the map that is the temporal nearest
neighbour in the future. Maps with equal time stamps are not modified
and must be removed or modified to create a valid temporal topology. In
case the last map in the space time dataset is a time instance, the
granularity of the space time dataset will be used to create the time
interval.
.SH EXAMPLE
A raster space time dataset will be create using precipitation maps for 2012
then using absolute time in a space time raster dataset using an increment
of one month.
At the end we snap the created time instances resulting in time intervals.
.br
.nf
\fC
# Generate data
t.create type=strds temporaltype=absolute \(rs
         output=precipitation_monthly \(rs
         title=\(dqMonthly precipitation\(dq \(rs
         description=\(dqDataset with monthly precipitation\(dq
t.register type=raster input=precipitation_monthly \(rs
           maps=\(gag.list type=raster pattern=\(dq2012*precip\(dq sep=comma\(ga \(rs
           start=2012\-01\-01 increment=\(dq1 months\(dq
# please take attention to \(dqTemporal type of maps\(dq value
t.info type=strds input=precipitation_monthly
 +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- Space Time Raster Dataset \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
 |                                                                            |
 +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- Basic information \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
 | Id: ........................ precipitation_monthly@climate_2009_2012
 | Name: ...................... precipitation_monthly
 | Mapset: .................... climate_2009_2012
 | Creator: ................... lucadelu
 | Temporal type: ............. absolute
 | Creation time: ............. 2014\-11\-28 15:52:30.801148
 | Modification time:.......... 2014\-11\-28 15:53:18.430773
 | Semantic type:.............. mean
 +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- Absolute time \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
 | Start time:................. 2012\-01\-01 00:00:00
 | End time:................... 2012\-12\-01 00:00:00
 | Granularity:................ 1 month
 | Temporal type of maps:...... point
 +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- Spatial extent \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
 | North:...................... 320000.0
 | South:...................... 10000.0
 | East:.. .................... 935000.0
 | West:....................... 120000.0
 | Top:........................ 0.0
 | Bottom:..................... 0.0
 +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- Metadata information \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
 | Raster register table:...... raster_map_register_282454f66ff5455299526ec3c1db7362
 | North\-South resolution min:. 500.0
 | North\-South resolution max:. 500.0
 | East\-west resolution min:... 500.0
 | East\-west resolution max:... 500.0
 | Minimum value min:.......... 0.0
 | Minimum value max:.......... 95.58169
 | Maximum value min:.......... 132.413284
 | Maximum value max:.......... 356.502949
 | Aggregation type:........... None
 | Number of registered maps:.. 12
 |
 | Title:
 | Monthly precipitation
 | Description:
 | Dataset with monthly precipitation
 | Command history:
 | # 2014\-11\-28 15:52:30
 | t.create type=\(dqstrds\(dq temporaltype=\(dqabsolute\(dq
 |     output=\(dqprecipitation_monthly\(dq title=\(dqMonthly precipitation\(dq
 |     description=\(dqDataset with monthly precipitation\(dq
 | # 2014\-11\-28 15:53:18
 | t.register type=\(dqrast\(dq input=\(dqprecipitation_monthly\(dq
 |     maps=\(dq2012_01_precip,2012_02_precip, ... ,2012_11_precip,2012_12_precip\(dq
 |     start=\(dq2012\-01\-01\(dq increment=\(dq1 months\(dq
 |
 +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
# you can see that end time is not set
t.rast.list input=precipitation_monthly
name|mapset|start_time|end_time
2012_01_precip|climate_2009_2012|2012\-01\-01 00:00:00|None
2012_02_precip|climate_2009_2012|2012\-02\-01 00:00:00|None
2012_03_precip|climate_2009_2012|2012\-03\-01 00:00:00|None
2012_04_precip|climate_2009_2012|2012\-04\-01 00:00:00|None
2012_05_precip|climate_2009_2012|2012\-05\-01 00:00:00|None
2012_06_precip|climate_2009_2012|2012\-06\-01 00:00:00|None
2012_07_precip|climate_2009_2012|2012\-07\-01 00:00:00|None
2012_08_precip|climate_2009_2012|2012\-08\-01 00:00:00|None
2012_09_precip|climate_2009_2012|2012\-09\-01 00:00:00|None
2012_10_precip|climate_2009_2012|2012\-10\-01 00:00:00|None
2012_11_precip|climate_2009_2012|2012\-11\-01 00:00:00|None
2012_12_precip|climate_2009_2012|2012\-12\-01 00:00:00|None
t.snap type=strds input=precipitation_monthly
# please take attention to \(dqTemporal type of maps\(dq value again
t.info type=strds input=precipitation_monthly
 +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- Space Time Raster Dataset \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
 |                                                                            |
 +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- Basic information \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
 | Id: ........................ precipitation_monthly@climate_2009_2012
 | Name: ...................... precipitation_monthly
 | Mapset: .................... climate_2009_2012
 | Creator: ................... lucadelu
 | Temporal type: ............. absolute
 | Creation time: ............. 2014\-11\-28 15:52:30.801148
 | Modification time:.......... 2014\-11\-28 15:54:28.739905
 | Semantic type:.............. mean
 +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- Absolute time \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
 | Start time:................. 2012\-01\-01 00:00:00
 | End time:................... 2013\-01\-01 00:00:00
 | Granularity:................ 1 month
 | Temporal type of maps:...... interval
 +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- Spatial extent \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
 | North:...................... 320000.0
 | South:...................... 10000.0
 | East:.. .................... 935000.0
 | West:....................... 120000.0
 | Top:........................ 0.0
 | Bottom:..................... 0.0
 +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- Metadata information \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
 | Raster register table:...... raster_map_register_282454f66ff5455299526ec3c1db7362
 | North\-South resolution min:. 500.0
 | North\-South resolution max:. 500.0
 | East\-west resolution min:... 500.0
 | East\-west resolution max:... 500.0
 | Minimum value min:.......... 0.0
 | Minimum value max:.......... 95.58169
 | Maximum value min:.......... 132.413284
 | Maximum value max:.......... 356.502949
 | Aggregation type:........... None
 | Number of registered maps:.. 12
 |
 | Title:
 | Monthly precipitation
 | Description:
 | Dataset with monthly precipitation
 | Command history:
 | # 2014\-11\-28 15:52:30
 | t.create type=\(dqstrds\(dq temporaltype=\(dqabsolute\(dq
 |     output=\(dqprecipitation_monthly\(dq title=\(dqMonthly precipitation\(dq
 |     description=\(dqDataset with monthly precipitation\(dq
 | # 2014\-11\-28 15:53:18
 | t.register type=\(dqrast\(dq input=\(dqprecipitation_monthly\(dq
 |     maps=\(dq2012_01_precip,2012_02_precip, ... ,2012_11_precip,2012_12_precip\(dq
 |     start=\(dq2012\-01\-01\(dq increment=\(dq1 months\(dq
 | # 2014\-11\-28 15:54:28
 | t.snap type=\(dqstrds\(dq input=\(dqprecipitation_monthly\(dq
 |
 +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
# now instead end time is set
t.rast.list input=precipitation_daily
2012_01_precip|climate_2009_2012|2012\-01\-01 00:00:00|2012\-02\-01 00:00:00
2012_02_precip|climate_2009_2012|2012\-02\-01 00:00:00|2012\-03\-01 00:00:00
2012_03_precip|climate_2009_2012|2012\-03\-01 00:00:00|2012\-04\-01 00:00:00
2012_04_precip|climate_2009_2012|2012\-04\-01 00:00:00|2012\-05\-01 00:00:00
2012_05_precip|climate_2009_2012|2012\-05\-01 00:00:00|2012\-06\-01 00:00:00
2012_06_precip|climate_2009_2012|2012\-06\-01 00:00:00|2012\-07\-01 00:00:00
2012_07_precip|climate_2009_2012|2012\-07\-01 00:00:00|2012\-08\-01 00:00:00
2012_08_precip|climate_2009_2012|2012\-08\-01 00:00:00|2012\-09\-01 00:00:00
2012_09_precip|climate_2009_2012|2012\-09\-01 00:00:00|2012\-10\-01 00:00:00
2012_10_precip|climate_2009_2012|2012\-10\-01 00:00:00|2012\-11\-01 00:00:00
2012_11_precip|climate_2009_2012|2012\-11\-01 00:00:00|2012\-12\-01 00:00:00
2012_12_precip|climate_2009_2012|2012\-12\-01 00:00:00|2013\-01\-01 00:00:00
\fR
.fi
.SH SEE ALSO
\fI
t.shift,
t.create,
t.register
\fR
.SH AUTHOR
Sören Gebbert, Thünen Institute of Climate\-Smart Agriculture
.SH SOURCE CODE
.PP
Available at: t.snap source code (history)
.PP
Main index |
Temporal index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2021
GRASS Development Team,
GRASS GIS 7.8.6RC3 Reference Manual
