.TH topic_vegetation_index 1 "" "GRASS 7.8.6RC1" "GRASS GIS User's Manual"
.SH Topic: vegetation index
.TS
expand;
lw60 lw1 lw60.
T{
i.vi
T}	 	T{
Calculates different types of vegetation indices.
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword vegetation index for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2021
GRASS Development Team,
GRASS GIS 7.8.6RC1 Reference Manual
