.TH topic_classification 1 "" "GRASS 7.8.7" "GRASS GIS User's Manual"
.SH Topic: classification
.TS
expand;
lw60 lw1 lw60.
T{
i.cluster
T}	 	T{
Generates spectral signatures for land cover types in an image using a clustering algorithm.
T}
.sp 1
T{
i.gensig
T}	 	T{
Generates statistics for i.maxlik from raster map.
T}
.sp 1
T{
i.gensigset
T}	 	T{
Generates statistics for i.smap from raster map.
T}
.sp 1
T{
i.maxlik
T}	 	T{
Classifies the cell spectral reflectances in imagery data.
T}
.sp 1
T{
i.smap
T}	 	T{
Performs contextual image classification using sequential maximum a posteriori (SMAP) estimation.
T}
.sp 1
T{
v.class
T}	 	T{
Classifies attribute data, e.g. for thematic mapping
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword classification for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2022
GRASS Development Team,
GRASS GIS 7.8.7 Reference Manual
