.TH topic_LIDAR 1 "" "GRASS 7.8.6RC1" "GRASS GIS User's Manual"
.SH Topic: LIDAR
.TS
expand;
lw60 lw1 lw60.
T{
v.decimate
T}	 	T{
Decimates a point cloud
T}
.sp 1
T{
v.lidar.correction
T}	 	T{
Corrects the v.lidar.growing output. It is the last of the three algorithms for LIDAR filtering.
T}
.sp 1
T{
v.lidar.edgedetection
T}	 	T{
Detects the object\(cqs edges from a LIDAR data set.
T}
.sp 1
T{
v.lidar.growing
T}	 	T{
Building contour determination and Region Growing algorithm for determining the building inside
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword LIDAR for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2021
GRASS Development Team,
GRASS GIS 7.8.6RC1 Reference Manual
