.TH topic_extract 1 "" "GRASS 7.8.6RC1" "GRASS GIS User's Manual"
.SH Topic: extract
.TS
expand;
lw60 lw1 lw60.
T{
t.rast.extract
T}	 	T{
Extracts a subset of a space time raster datasets.
T}
.sp 1
T{
t.rast3d.extract
T}	 	T{
Extracts a subset of a space time 3D raster dataset.
T}
.sp 1
T{
t.vect.extract
T}	 	T{
Extracts a subset of a space time vector dataset.
T}
.sp 1
T{
v.extract
T}	 	T{
Selects vector features from an existing vector map and creates a new vector map containing only the selected features.
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword extract for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2021
GRASS Development Team,
GRASS GIS 7.8.6RC1 Reference Manual
