.TH topic_gradient 1 "" "GRASS 7.8.7" "GRASS GIS User's Manual"
.SH Topic: gradient
.TS
expand;
lw60 lw1 lw60.
T{
r3.gradient
T}	 	T{
Computes gradient of a 3D raster map and outputs gradient components as three 3D raster maps.
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword gradient for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2022
GRASS Development Team,
GRASS GIS 7.8.7 Reference Manual
