.TH topic_orthorectify 1 "" "GRASS 7.8.7" "GRASS GIS User's Manual"
.SH Topic: orthorectify
.TS
expand;
lw60 lw1 lw60.
T{
i.ortho.camera
T}	 	T{
Select and modify the imagery group camera reference file.
T}
.sp 1
T{
i.ortho.elev
T}	 	T{
Select or modify the target elevation model.
T}
.sp 1
T{
i.ortho.init
T}	 	T{
Interactively creates or modifies entries in a camera initial exposure station file for imagery group referenced by a sub\-block.
T}
.sp 1
T{
i.ortho.photo
T}	 	T{
Menu driver for the photo imagery programs.
T}
.sp 1
T{
i.ortho.rectify
T}	 	T{
Orthorectifies an image by using the image to photo coordinate transformation matrix.
T}
.sp 1
T{
i.ortho.target
T}	 	T{
Select or modify the imagery group target.
T}
.sp 1
T{
i.ortho.transform
T}	 	T{
Computes a coordinate transformation based on the control points.
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword orthorectify for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2022
GRASS Development Team,
GRASS GIS 7.8.7 Reference Manual
