.TH topic_radiometric_conversion 1 "" "GRASS 7.8.7" "GRASS GIS User's Manual"
.SH Topic: radiometric conversion
.TS
expand;
lw60 lw1 lw60.
T{
i.aster.toar
T}	 	T{
Calculates Top of Atmosphere Radiance/Reflectance/Brightness Temperature from ASTER DN.
T}
.sp 1
T{
i.landsat.toar
T}	 	T{
Calculates top\-of\-atmosphere radiance or reflectance and temperature for Landsat MSS/TM/ETM+/OLI
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword radiometric conversion for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2022
GRASS Development Team,
GRASS GIS 7.8.7 Reference Manual
