.TH topic_querying 1 "" "GRASS 7.8.6RC1" "GRASS GIS User's Manual"
.SH Topic: querying
.TS
expand;
lw60 lw1 lw60.
T{
i.spectral
T}	 	T{
Displays spectral response at user specified locations in group or images.
T}
.sp 1
T{
r.what.color
T}	 	T{
Queries colors for a raster map layer.
T}
.sp 1
T{
r.what
T}	 	T{
Queries raster maps on their category values and category labels.
T}
.sp 1
T{
v.what
T}	 	T{
Queries a vector map at given locations.
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword querying for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2021
GRASS Development Team,
GRASS GIS 7.8.6RC1 Reference Manual
