.TH topic_category 1 "" "GRASS 7.8.6RC1" "GRASS GIS User's Manual"
.SH Topic: category
.TS
expand;
lw60 lw1 lw60.
T{
r.category
T}	 	T{
Manages category values and labels associated with user\-specified raster map layers.
T}
.sp 1
T{
v.category
T}	 	T{
Attaches, deletes or reports vector categories to/from/of map geometry.
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword category for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2021
GRASS Development Team,
GRASS GIS 7.8.6RC1 Reference Manual
