.TH topic_fire 1 "" "GRASS 7.8.7" "GRASS GIS User's Manual"
.SH Topic: fire
.TS
expand;
lw60 lw1 lw60.
T{
r.ros
T}	 	T{
Generates rate of spread raster maps.
T}
.sp 1
T{
r.spread
T}	 	T{
Simulates elliptically anisotropic spread.
T}
.sp 1
T{
r.spreadpath
T}	 	T{
Recursively traces the least cost path backwards to cells from which the cumulative cost was determined.
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword fire for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2022
GRASS Development Team,
GRASS GIS 7.8.7 Reference Manual
