.TH topic_color_table 1 "" "GRASS 7.8.7" "GRASS GIS User's Manual"
.SH Topic: color table
.TS
expand;
lw60 lw1 lw60.
T{
r.colors
T}	 	T{
Creates/modifies the color table associated with a raster map.
T}
.sp 1
T{
r.colors.out
T}	 	T{
Exports the color table associated with a raster map.
T}
.sp 1
T{
r.colors.stddev
T}	 	T{
Sets color rules based on stddev from a raster map\(cqs mean value.
T}
.sp 1
T{
r3.colors
T}	 	T{
Creates/modifies the color table associated with a 3D raster map.
T}
.sp 1
T{
r3.colors.out
T}	 	T{
Exports the color table associated with a 3D raster map.
T}
.sp 1
T{
t.rast.colors
T}	 	T{
Creates/modifies the color table associated with each raster map of the space time raster dataset.
T}
.sp 1
T{
v.colors
T}	 	T{
Creates/modifies the color table associated with a vector map.
T}
.sp 1
T{
v.colors.out
T}	 	T{
Exports the color table associated with a vector map.
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword color table for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2022
GRASS Development Team,
GRASS GIS 7.8.7 Reference Manual
