.TH topic_null_data 1 "" "GRASS 7.8.6RC1" "GRASS GIS User's Manual"
.SH Topic: null data
.TS
expand;
lw60 lw1 lw60.
T{
r.null
T}	 	T{
Manages NULL\-values of given raster map.
T}
.sp 1
T{
r3.null
T}	 	T{
Explicitly create the 3D NULL\-value bitmap file.
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword null data for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2021
GRASS Development Team,
GRASS GIS 7.8.6RC1 Reference Manual
