.TH topic_elevation 1 "" "GRASS 7.8.6RC1" "GRASS GIS User's Manual"
.SH Topic: elevation
.TS
expand;
lw60 lw1 lw60.
T{
d.shade
T}	 	T{
Drapes a color raster over an shaded relief or aspect map.
T}
.sp 1
T{
r.plane
T}	 	T{
Creates raster plane map given dip (inclination), aspect (azimuth) and one point.
T}
.sp 1
T{
r.relief
T}	 	T{
Creates shaded relief map from an elevation map (DEM).
T}
.sp 1
T{
r.shade
T}	 	T{
Drapes a color raster over an shaded relief or aspect map.
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword elevation for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2021
GRASS Development Team,
GRASS GIS 7.8.6RC1 Reference Manual
