.TH topic_graphics 1 "" "GRASS 7.8.7" "GRASS GIS User's Manual"
.SH Topic: graphics
.TS
expand;
lw60 lw1 lw60.
T{
d.erase
T}	 	T{
Erases the contents of the active graphics display frame with user defined color.
T}
.sp 1
T{
d.frame
T}	 	T{
Manages display frames on the user\(cqs graphics monitor.
T}
.sp 1
T{
d.his
T}	 	T{
Displays the result obtained by combining hue, intensity, and saturation (HIS) values from user\-specified input raster map layers.
T}
.sp 1
T{
d.info
T}	 	T{
Displays information about the active display monitor.
T}
.sp 1
T{
d.mon
T}	 	T{
Controls graphics display monitors from the command line.
T}
.sp 1
T{
d.rast
T}	 	T{
Displays user\-specified raster map in the active graphics frame.
T}
.sp 1
T{
d.redraw
T}	 	T{
Redraws the content of currently selected monitor.
T}
.sp 1
T{
d.rgb
T}	 	T{
Displays three user\-specified raster maps as red, green, and blue overlays in the active graphics frame.
T}
.sp 1
T{
d.vect
T}	 	T{
Displays user\-specified vector map in the active graphics frame.
T}
.sp 1
T{
m.nviz.script
T}	 	T{
Creates fly\-through script to run in NVIZ.
T}
.sp 1
T{
wxpyimgview
T}	 	T{
Views BMP images from the PNG driver.
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword graphics for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2022
GRASS Development Team,
GRASS GIS 7.8.7 Reference Manual
