.TH topic_distance 1 "" "GRASS 7.8.6RC1" "GRASS GIS User's Manual"
.SH Topic: distance
.TS
expand;
lw60 lw1 lw60.
T{
d.geodesic
T}	 	T{
Displays a geodesic line, tracing the shortest distance between two geographic points along a great circle, in a longitude/latitude data set.
T}
.sp 1
T{
d.rhumbline
T}	 	T{
Displays the rhumbline joining two longitude/latitude coordinates.
T}
.sp 1
T{
m.cogo
T}	 	T{
A simple utility for converting bearing and distance measurements to coordinates and vice versa.
T}
.sp 1
T{
r.distance
T}	 	T{
Locates the closest points between objects in two raster maps.
T}
.sp 1
T{
r.grow.distance
T}	 	T{
Generates a raster map containing distances to nearest raster features and/or the value of the nearest non\-null cell.
T}
.sp 1
T{
r.grow
T}	 	T{
Generates a raster map layer with contiguous areas grown by one cell.
T}
.sp 1
T{
v.distance
T}	 	T{
Finds the nearest element in vector map \(cqto\(cq for elements in vector map \(cqfrom\(cq.
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword distance for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2021
GRASS Development Team,
GRASS GIS 7.8.6RC1 Reference Manual
