.TH topic_biomass 1 "" "GRASS 7.8.7" "GRASS GIS User's Manual"
.SH Topic: biomass
.TS
expand;
lw60 lw1 lw60.
T{
i.biomass
T}	 	T{
Computes biomass growth, precursor of crop yield calculation.
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword biomass for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2022
GRASS Development Team,
GRASS GIS 7.8.7 Reference Manual
