.TH topic_conversion 1 "" "GRASS 7.8.6RC1" "GRASS GIS User's Manual"
.SH Topic: conversion
.TS
expand;
lw60 lw1 lw60.
T{
r.to.rast3
T}	 	T{
Converts 2D raster map slices to one 3D raster volume map.
T}
.sp 1
T{
r.to.rast3elev
T}	 	T{
Creates a 3D volume map based on 2D elevation and value raster maps.
T}
.sp 1
T{
r.to.vect
T}	 	T{
Converts a raster map into a vector map.
T}
.sp 1
T{
r3.to.rast
T}	 	T{
Converts 3D raster maps to 2D raster maps
T}
.sp 1
T{
t.rast.to.rast3
T}	 	T{
Converts a space time raster dataset into a 3D raster map.
T}
.sp 1
T{
t.rast.to.vect
T}	 	T{
Converts a space time raster dataset into a space time vector dataset
T}
.sp 1
T{
v.to.rast
T}	 	T{
Converts (rasterize) a vector map into a raster map.
T}
.sp 1
T{
v.to.rast3
T}	 	T{
Converts a vector map (only points) into a 3D raster map.
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword conversion for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2021
GRASS Development Team,
GRASS GIS 7.8.6RC1 Reference Manual
