.TH topic_color_transformation 1 "" "GRASS 7.8.6RC1" "GRASS GIS User's Manual"
.SH Topic: color transformation
.TS
expand;
lw60 lw1 lw60.
T{
i.his.rgb
T}	 	T{
Transforms raster maps from HIS (Hue\-Intensity\-Saturation) color space to RGB (Red\-Green\-Blue) color space.
T}
.sp 1
T{
i.rgb.his
T}	 	T{
Transforms raster maps from RGB (Red\-Green\-Blue) color space to HIS (Hue\-Intensity\-Saturation) color space.
T}
.sp 1
T{
r.his
T}	 	T{
Generates red, green and blue (RGB) raster map layers combining hue, intensity and saturation (HIS) values from user\-specified input raster map layers.
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword color transformation for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2021
GRASS Development Team,
GRASS GIS 7.8.6RC1 Reference Manual
