.TH topic_time_management 1 "" "GRASS 7.8.7" "GRASS GIS User's Manual"
.SH Topic: time management
.TS
expand;
lw60 lw1 lw60.
T{
t.merge
T}	 	T{
Merges several space time datasets into a single space time dataset.
T}
.sp 1
T{
t.shift
T}	 	T{
Shifts temporally the maps of a space time dataset.
T}
.sp 1
T{
t.snap
T}	 	T{
Snaps temporally the maps of a space time dataset.
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword time management for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2022
GRASS Development Team,
GRASS GIS 7.8.7 Reference Manual
