.TH topic_aggregation 1 "" "GRASS 7.8.6RC1" "GRASS GIS User's Manual"
.SH Topic: aggregation
.TS
expand;
lw60 lw1 lw60.
T{
r.series
T}	 	T{
Makes each output cell value a function of the values assigned to the corresponding cells in the input raster map layers.
T}
.sp 1
T{
t.rast.aggregate.ds
T}	 	T{
Aggregates data of an existing space time raster dataset using the time intervals of a second space time dataset.
T}
.sp 1
T{
t.rast.aggregate
T}	 	T{
Aggregates temporally the maps of a space time raster dataset by a user defined granularity.
T}
.sp 1
T{
t.rast.neighbors
T}	 	T{
Performs a neighborhood analysis for each map in a space time raster dataset.
T}
.sp 1
T{
t.rast.series
T}	 	T{
Performs different aggregation algorithms from r.series on all or a subset of raster maps in a space time raster dataset.
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword aggregation for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2021
GRASS Development Team,
GRASS GIS 7.8.6RC1 Reference Manual
