.TH topic_imagery_quality_assessment 1 "" "GRASS 7.8.6RC1" "GRASS GIS User's Manual"
.SH Topic: imagery quality assessment
.TS
expand;
lw60 lw1 lw60.
T{
i.modis.qc
T}	 	T{
Extracts quality control parameters from MODIS QC layers.
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword imagery quality assessment for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2021
GRASS Development Team,
GRASS GIS 7.8.6RC1 Reference Manual
