.TH topic_installation 1 "" "GRASS 7.8.6RC1" "GRASS GIS User's Manual"
.SH Topic: installation
.TS
expand;
lw60 lw1 lw60.
T{
g.extension.all
T}	 	T{
Rebuilds or removes all locally installed GRASS Addons extensions.
T}
.sp 1
T{
g.extension
T}	 	T{
Maintains GRASS Addons extensions in local GRASS installation.
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword installation for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2021
GRASS Development Team,
GRASS GIS 7.8.6RC1 Reference Manual
