.TH topic_resample 1 "" "GRASS 7.8.6RC1" "GRASS GIS User's Manual"
.SH Topic: resample
.TS
expand;
lw60 lw1 lw60.
T{
r.resamp.filter
T}	 	T{
Resamples raster map layers using an analytic kernel.
T}
.sp 1
T{
r.resamp.interp
T}	 	T{
Resamples raster map to a finer grid using interpolation.
T}
.sp 1
T{
r.resamp.rst
T}	 	T{
Reinterpolates and optionally computes topographic analysis from input raster map to a new raster map (possibly with different resolution) using regularized spline with tension and smoothing.
T}
.sp 1
T{
r.resamp.stats
T}	 	T{
Resamples raster map layers to a coarser grid using aggregation.
T}
.sp 1
T{
r.resample
T}	 	T{
GRASS raster map layer data resampling capability.
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword resample for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2021
GRASS Development Team,
GRASS GIS 7.8.6RC1 Reference Manual
