.TH topic_tiling 1 "" "GRASS 7.8.6RC1" "GRASS GIS User's Manual"
.SH Topic: tiling
.TS
expand;
lw60 lw1 lw60.
T{
r.tile
T}	 	T{
Splits a raster map into tiles.
T}
.sp 1
T{
r.tileset
T}	 	T{
Produces tilings of the source projection for use in the destination region and projection.
T}
.sp 1
T{
r3.retile
T}	 	T{
Retiles an existing 3D raster map with user defined x, y and z tile size.
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword tiling for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2021
GRASS Development Team,
GRASS GIS 7.8.6RC1 Reference Manual
