.TH topic_segmentation 1 "" "GRASS 7.8.7" "GRASS GIS User's Manual"
.SH Topic: segmentation
.TS
expand;
lw60 lw1 lw60.
T{
i.segment
T}	 	T{
Identifies segments (objects) from imagery data.
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword segmentation for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2022
GRASS Development Team,
GRASS GIS 7.8.7 Reference Manual
