.TH topic_vector 1 "" "GRASS 7.8.6RC1" "GRASS GIS User's Manual"
.SH Topic: vector
.TS
expand;
lw60 lw1 lw60.
T{
d.what.rast
T}	 	T{
Allows the user to interactively query raster map layers at user\-selected locations.
T}
.sp 1
T{
d.what.vect
T}	 	T{
Allows the user to interactively query vector map layers at user\-selected locations.
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword vector for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2021
GRASS Development Team,
GRASS GIS 7.8.6RC1 Reference Manual
