.TH topic_linear_reference_system 1 "" "GRASS 7.8.6RC1" "GRASS GIS User's Manual"
.SH Topic: linear reference system
.TS
expand;
lw60 lw1 lw60.
T{
v.lrs.create
T}	 	T{
Creates a linear reference system.
T}
.sp 1
T{
v.lrs.label
T}	 	T{
Creates stationing from input lines, and linear reference system.
T}
.sp 1
T{
v.lrs.segment
T}	 	T{
Creates points/segments from input lines, linear reference system and positions read from stdin or a file.
T}
.sp 1
T{
v.lrs.where
T}	 	T{
Finds line id and real km+offset for given points in vector map using linear reference system.
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword linear reference system for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2021
GRASS Development Team,
GRASS GIS 7.8.6RC1 Reference Manual
