.TH topic_multispectral 1 "" "GRASS 7.8.7" "GRASS GIS User's Manual"
.SH Topic: multispectral
.TS
expand;
lw60 lw1 lw60.
T{
i.oif
T}	 	T{
Calculates Optimum\-Index\-Factor table for spectral bands
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword multispectral for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2022
GRASS Development Team,
GRASS GIS 7.8.7 Reference Manual
