.TH topic_energy_balance 1 "" "GRASS 7.8.6RC1" "GRASS GIS User's Manual"
.SH Topic: energy balance
.TS
expand;
lw60 lw1 lw60.
T{
i.eb.eta
T}	 	T{
Actual evapotranspiration for diurnal period (Bastiaanssen, 1995).
T}
.sp 1
T{
i.eb.evapfr
T}	 	T{
Computes evaporative fraction and root zone soil moisture.
T}
.sp 1
T{
i.eb.hsebal01
T}	 	T{
Computes sensible heat flux iteration SEBAL 01.
T}
.sp 1
T{
i.eb.netrad
T}	 	T{
Net radiation approximation (Bastiaanssen, 1995).
T}
.sp 1
T{
i.eb.soilheatflux
T}	 	T{
Soil heat flux approximation (Bastiaanssen, 1995).
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword energy balance for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2021
GRASS Development Team,
GRASS GIS 7.8.6RC1 Reference Manual
