.TH topic_landscape_structure_analysis 1 "" "GRASS 7.8.6RC1" "GRASS GIS User's Manual"
.SH Topic: landscape structure analysis
.TS
expand;
lw60 lw1 lw60.
T{
r.li.cwed
T}	 	T{
Calculates contrast weighted edge density index on a raster map
T}
.sp 1
T{
r.li.dominance
T}	 	T{
Calculates dominance\(cqs diversity index on a raster map
T}
.sp 1
T{
r.li.edgedensity
T}	 	T{
Calculates edge density index on a raster map, using a 4 neighbour algorithm
T}
.sp 1
T{
r.li.mpa
T}	 	T{
Calculates mean pixel attribute index on a raster map
T}
.sp 1
T{
r.li.mps
T}	 	T{
Calculates mean patch size index on a raster map, using a 4 neighbour algorithm
T}
.sp 1
T{
r.li.padcv
T}	 	T{
Calculates coefficient of variation of patch area on a raster map
T}
.sp 1
T{
r.li.padrange
T}	 	T{
Calculates range of patch area size on a raster map
T}
.sp 1
T{
r.li.padsd
T}	 	T{
Calculates standard deviation of patch area a raster map
T}
.sp 1
T{
r.li.patchdensity
T}	 	T{
Calculates patch density index on a raster map, using a 4 neighbour algorithm
T}
.sp 1
T{
r.li.patchnum
T}	 	T{
Calculates patch number index on a raster map, using a 4 neighbour algorithm.
T}
.sp 1
T{
r.li.pielou
T}	 	T{
Calculates Pielou\(cqs diversity index on a raster map
T}
.sp 1
T{
r.li.renyi
T}	 	T{
Calculates Renyi\(cqs diversity index on a raster map
T}
.sp 1
T{
r.li.richness
T}	 	T{
Calculates richness index on a raster map
T}
.sp 1
T{
r.li.shannon
T}	 	T{
Calculates Shannon\(cqs diversity index on a raster map
T}
.sp 1
T{
r.li.shape
T}	 	T{
Calculates shape index on a raster map
T}
.sp 1
T{
r.li.simpson
T}	 	T{
Calculates Simpson\(cqs diversity index on a raster map
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword landscape structure analysis for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2021
GRASS Development Team,
GRASS GIS 7.8.6RC1 Reference Manual
