.TH topic_profile 1 "" "GRASS 7.8.6RC1" "GRASS GIS User's Manual"
.SH Topic: profile
.TS
expand;
lw60 lw1 lw60.
T{
d.profile
T}	 	T{
Plots profile of a transect.
T}
.sp 1
T{
r.profile
T}	 	T{
Outputs the raster map layer values lying on user\-defined line(s).
T}
.sp 1
T{
r.transect
T}	 	T{
Outputs raster map layer values lying along user defined transect line(s).
T}
.sp 1
T{
r3.cross.rast
T}	 	T{
Creates cross section 2D raster map from 3D raster map based on 2D elevation map
T}
.sp 1
T{
v.profile
T}	 	T{
Vector map profiling tool
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword profile for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2021
GRASS Development Team,
GRASS GIS 7.8.6RC1 Reference Manual
