.TH topic_paint_labels 1 "" "GRASS 7.8.6RC1" "GRASS GIS User's Manual"
.SH Topic: paint labels
.TS
expand;
lw60 lw1 lw60.
T{
d.labels
T}	 	T{
Displays text labels (created with v.label) to the active frame on the graphics monitor.
T}
.sp 1
T{
v.label
T}	 	T{
Creates paint labels for a vector map from attached attributes.
T}
.sp 1
T{
v.label.sa
T}	 	T{
Create optimally placed labels for vector map(s)
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword paint labels for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2021
GRASS Development Team,
GRASS GIS 7.8.6RC1 Reference Manual
