.TH topic_settings 1 "" "GRASS 7.8.7" "GRASS GIS User's Manual"
.SH Topic: settings
.TS
expand;
lw60 lw1 lw60.
T{
d.colorlist
T}	 	T{
Outputs a list of all available display colors.
T}
.sp 1
T{
d.font
T}	 	T{
Selects the font in which text will be displayed on the user\(cqs graphics monitor.
T}
.sp 1
T{
d.fontlist
T}	 	T{
Lists the available fonts.
T}
.sp 1
T{
g.gisenv
T}	 	T{
Outputs and modifies the user\(cqs current GRASS variable settings.
T}
.sp 1
T{
g.mapset
T}	 	T{
Changes/reports current mapset.
T}
.sp 1
T{
g.mapsets
T}	 	T{
Modifies/prints the user\(cqs current mapset search path.
T}
.sp 1
T{
g.region
T}	 	T{
Manages the boundary definitions for the geographic region.
T}
.sp 1
T{
t.connect
T}	 	T{
Prints/sets general temporal GIS database connection for current mapset.
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword settings for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2022
GRASS Development Team,
GRASS GIS 7.8.7 Reference Manual
