.TH v.outlier 1 "" "GRASS 7.8.6RC3" "GRASS GIS User's Manual"
.SH NAME
\fI\fBv.outlier\fR\fR  \- Removes outliers from vector point data.
.SH KEYWORDS
vector, statistics, extract, select, filter, LIDAR
.SH SYNOPSIS
\fBv.outlier\fR
.br
\fBv.outlier \-\-help\fR
.br
\fBv.outlier\fR [\-\fBe\fR] \fBinput\fR=\fIname\fR \fBoutput\fR=\fIname\fR \fBoutlier\fR=\fIname\fR  [\fBqgis\fR=\fIname\fR]   [\fBew_step\fR=\fIfloat\fR]   [\fBns_step\fR=\fIfloat\fR]   [\fBlambda\fR=\fIfloat\fR]   [\fBthreshold\fR=\fIfloat\fR]   [\fBfilter\fR=\fIstring\fR]   [\-\-\fBoverwrite\fR]  [\-\-\fBhelp\fR]  [\-\-\fBverbose\fR]  [\-\-\fBquiet\fR]  [\-\-\fBui\fR]
.SS Flags:
.IP "\fB\-e\fR" 4m
.br
Estimate point density and distance
.br
Estimate point density and distance for the input vector points within the current region extends and quit
.IP "\fB\-\-overwrite\fR" 4m
.br
Allow output files to overwrite existing files
.IP "\fB\-\-help\fR" 4m
.br
Print usage summary
.IP "\fB\-\-verbose\fR" 4m
.br
Verbose module output
.IP "\fB\-\-quiet\fR" 4m
.br
Quiet module output
.IP "\fB\-\-ui\fR" 4m
.br
Force launching GUI dialog
.SS Parameters:
.IP "\fBinput\fR=\fIname\fR \fB[required]\fR" 4m
.br
Name of input vector map
.br
Or data source for direct OGR access
.IP "\fBoutput\fR=\fIname\fR \fB[required]\fR" 4m
.br
Name for output vector map
.IP "\fBoutlier\fR=\fIname\fR \fB[required]\fR" 4m
.br
Name for output outlier vector map
.IP "\fBqgis\fR=\fIname\fR" 4m
.br
Name for vector map for visualization in QGIS
.IP "\fBew_step\fR=\fIfloat\fR" 4m
.br
Length of each spline step in the east\-west direction
.br
Default: 10 * east\-west resolution
.IP "\fBns_step\fR=\fIfloat\fR" 4m
.br
Length of each spline step in the north\-south direction
.br
Default: 10 * north\-south resolution
.IP "\fBlambda\fR=\fIfloat\fR" 4m
.br
Tykhonov regularization weight
.br
Default: \fI0.1\fR
.IP "\fBthreshold\fR=\fIfloat\fR" 4m
.br
Threshold for the outliers
.br
Default: \fI50\fR
.IP "\fBfilter\fR=\fIstring\fR" 4m
.br
Filtering option
.br
Options: \fIboth, positive, negative\fR
.br
Default: \fIboth\fR
.SH DESCRIPTION
\fIv.outlier\fR removes outliers in a 3D point cloud. By default, the outlier
identification is done by a bicubic spline interpolation of the
observation with a high regularization parameter and a low resolution
in south\-north and east\-west directions. Those points that differ in
an absolute value more than the given threshold from a fixed value,
reckoned from its surroundings by the interpolation, are considered as
an outlier, and hence are removed.
.PP
The \fIfilter\fR option specifies if all outliers will be removed
(default), or only positive or only negative outliers. Filtering out
only positive outliers can be useful to filter out vegetation returns
(e.g. from forest canopies) from LIDAR point clouds, in order to
extract Digital Terrain Models. Filtering out only negative outliers
can be useful to estimate vegetation height.
.PP
There is a flag to create a vector that can be visualizated by
qgis. That means that topology is build and the z coordinate is
considered as a category.
.SH EXAMPLES
.SS Basic outlier removal
.br
.nf
\fC
v.outlier input=vector_map output=vector_output outlier=vector_outlier thres_O=25
\fR
.fi
In this case, a basic outlier removal is done with a threshold of 25 m.
.SS Basic outlier removal
.br
.nf
\fC
v.outlier input=vector_map output=vector_output outlier=vector_outlier qgis=vector_qgis
\fR
.fi
Now, the outlier removal uses the default threshold and there is also
an output vector available for visualizaton in QGIS
(http://www.qgis.org).
.SS North carolina location example
.br
.nf
\fC
v.outlier input=elev_lid792_bepts output=elev_lid792_bepts_nooutliers \(rs
  outlier=elev_lid792_bepts_outliers ew_step=5 ns_step=5 thres_o=0.1
\fR
.fi
.SH NOTES
This module is designed to work with LIDAR data, so not topology is
built but in the QGIS output.
.SH SEE ALSO
\fIv.surf.bspline\fR
.SH AUTHORS
Original version of the program in GRASS 5.4:
.br
Maria Antonia Brovelli, Massimiliano Cannata, Ulisse Longoni and Mirko Reguzzoni
.br
.br
Updates for GRASS 6:
.br
Roberto Antolin
.SH SOURCE CODE
.PP
Available at: v.outlier source code (history)
.PP
Main index |
Vector index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2021
GRASS Development Team,
GRASS GIS 7.8.6RC3 Reference Manual
