.TH v.pack 1 "" "GRASS 7.8.7" "GRASS GIS User's Manual"
.SH NAME
\fI\fBv.pack.py\fR\fR  \- Exports a vector map as GRASS GIS specific archive file
.SH KEYWORDS
vector, export, copying
.SH SYNOPSIS
\fBv.pack.py\fR
.br
\fBv.pack.py \-\-help\fR
.br
\fBv.pack.py\fR [\-\fBc\fR] \fBinput\fR=\fIname\fR  [\fBoutput\fR=\fIname\fR]   [\-\-\fBoverwrite\fR]  [\-\-\fBhelp\fR]  [\-\-\fBverbose\fR]  [\-\-\fBquiet\fR]  [\-\-\fBui\fR]
.SS Flags:
.IP "\fB\-c\fR" 4m
.br
Switch the compression off
.IP "\fB\-\-overwrite\fR" 4m
.br
Allow output files to overwrite existing files
.IP "\fB\-\-help\fR" 4m
.br
Print usage summary
.IP "\fB\-\-verbose\fR" 4m
.br
Verbose module output
.IP "\fB\-\-quiet\fR" 4m
.br
Quiet module output
.IP "\fB\-\-ui\fR" 4m
.br
Force launching GUI dialog
.SS Parameters:
.IP "\fBinput\fR=\fIname\fR \fB[required]\fR" 4m
.br
Name of vector map to pack up
.IP "\fBoutput\fR=\fIname\fR" 4m
.br
Name for output file (default is <input>.pack)
.SH DESCRIPTION
\fIv.pack\fR collects (packs) vector map elements and support files
in GRASS Database and creates an compressed file using \fIgzip\fR
algorithm. This file can be used to copy the vector map to another
machine. The packed file can be afterwards unpacked
by \fIv.unpack\fR.
.SH NOTES
Name of the pack file is determined by default from \fBinput\fR
parameter. Optionally the name can be given by \fBoutput\fR parameter.
.SH EXAMPLE
Pack up vector map \fIrandom_point\fR into \fIrandom_point.pack\fR file.
.br
.nf
\fC
v.pack input=random_point
\fR
.fi
the vector map can be afterwards unpacked by
.br
.nf
\fC
v.unpack input=random_point.pack
\fR
.fi
.SH SEE ALSO
\fI
v.unpack,
v.in.ogr,
g.copy,
v.proj,
r.unpack
\fR
.SH AUTHORS
Luca Delucchi, Fondazione E. Mach (Italy), based on the \fIr.pack\fR code
.SH SOURCE CODE
.PP
Available at:
v.pack source code
(history)
.PP
Accessed: unknown
.PP
Main index |
Vector index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2022
GRASS Development Team,
GRASS GIS 7.8.7 Reference Manual
