.TH wxGUI.dbmgr 1 "" "GRASS 7.8.6RC3" "GRASS GIS User's Manual"
.SH wxGUI Attribute Table Manager
.SH DESCRIPTION
The \fBAttribute Table Manager\fR is
a \fIwxGUI\fR compoment to query, edit,
and manage attribute data for vector maps. The attribute table manager
can be launched by clicking on icon  in the toolbar. It\(cqs also available as a stand\-alone
module \fIg.gui.dbmgr\fR.
.PP
\fIAttribute table manager\fR allows you to:
.RS 4n
.IP \(bu 4n
browse attribute data of vector map, perform SQL select
statements;
.IP \(bu 4n
modify attribute data, insert new records to attribute table,
delete existing records;
.IP \(bu 4n
highlight selected items in the Map Display Window;
.IP \(bu 4n
extract selected items into a new vector map;
.IP \(bu 4n
modify attribute table \- add, drop, rename columns;
.IP \(bu 4n
modify vector map DB connection settings \- add, remove or
modify layers.
.RE
.br
\fIFigure: Simple attribute filtering using Attribute Table Manager.\fR
.SS SQL Builder
.br
\fIFigure: Attribute filtering using Attribute Table Manager and SQL Builder.\fR
.SH SEE ALSO
\fI
wxGUI
.br
wxGUI components
\fR
.PP
\fI
db.columns,
db.connect,
db.describe,
db.drivers,
db.execute,
db.select,
db.tables
\fR
.PP
\fI
v.db.addcolumn,
v.db.connect,
v.db.dropcolumn,
v.db.renamecolumn,
v.what
\fR
.PP
See
also wiki
page
including video
tutorials.
.SH AUTHORS
Martin Landa, FBK\-irst (2007\-2008),
Trento, Italy, and OSGeoREL at the Czech Technical
University in Prague, Czech Republic
.br
Michael Barton, Arizona State University, USA
.br
Jachym Cepicky
.SH SOURCE CODE
.PP
Available at: wxGUI Attribute Table Manager source code (history)
.PP
Main index |
GUI index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2021
GRASS Development Team,
GRASS GIS 7.8.6RC3 Reference Manual
