QT.pdf.VERSION = 5.15.2
QT.pdf.name = QtPdf
QT.pdf.module = Qt5Pdf
QT.pdf.libs = $$QT_MODULE_LIB_BASE
QT.pdf.includes = $$QT_MODULE_INCLUDE_BASE $$QT_MODULE_INCLUDE_BASE/QtPdf
QT.pdf.frameworks =
QT.pdf.bins = $$QT_MODULE_BIN_BASE
QT.pdf.depends = core gui
QT.pdf.run_depends = network
QT.pdf.uses =
QT.pdf.module_config = v2
QT.pdf.DEFINES = QT_PDF_LIB
QT.pdf.enabled_features =
QT.pdf.disabled_features =
QT_CONFIG +=
QT_MODULES += pdf
